package report

import (
	"fmt"
	"image"
	"log"
	"os"
	"path/filepath"
	"strings"

	"github.com/threagile/threagile/pkg/types"
)

func (adoc adocReport) targetDescription(f *os.File, baseFolder string) {
	writeLine(f, "= Application Overview")
	writeLine(f, "== Business Criticality\n")
	writeLine(f, "The overall business criticality of \""+adoc.model.Title+"\" was rated as:\n")

	critString := "( "
	criticality := adoc.model.BusinessCriticality
	first := true
	for _, critValue := range types.CriticalityValues() {
		if !first {
			critString += " |"
		}
		if critValue == criticality {
			critString += " [.underline]#*" + strings.ToUpper(critValue.String()) + "*#"
		} else {
			critString += " [GreyText]#" + critValue.String() + "#"
		}
		first = false
	}
	critString += "  )"
	writeLine(f, critString)

	writeLine(f, "\n\n")
	writeLine(f, "== Business Overview")
	writeLine(f, fixBasicHtml(adoc.model.BusinessOverview.Description))
	addCustomImages(f, adoc.model.BusinessOverview.Images, baseFolder)

	writeLine(f, "\n\n")
	writeLine(f, "== Technical Overview")
	writeLine(f, fixBasicHtml(adoc.model.TechnicalOverview.Description))
	addCustomImages(f, adoc.model.TechnicalOverview.Images, baseFolder)
}

func (adoc adocReport) writeTargetDescription(baseFolder string) error {
	filename := "050_TargetDescription.adoc"
	td, err := os.Create(filepath.Join(adoc.targetDirectory, filename))
	defer func() { _ = td.Close() }()
	if err != nil {
		return err
	}
	adoc.writeMainLine("<<<")
	adoc.writeMainLine("include::" + filename + "[leveloffset=+1]")

	adoc.targetDescription(td, baseFolder)
	return nil
}

func (adoc adocReport) dataFlowDiagram(f *os.File, diagramFilenamePNG string) {
	writeLine(f, "= Data-Flow Diagram")
	// intermediate newlines are ignored in asciidoctor
	writeLine(f, `
The following diagram was generated by Threagile based on the model input and gives a high-level overview of the data-flow
between technical assets. The RAA value is the calculated _Relative Attacker Attractiveness_ in percent.
For a full high-resolution version of this diagram please refer to the PNG image file alongside this report.
	`)
	if diagramFilenamePNG == "" {
		writeLine(f, "\nThe diagram image file is not available (e.g. because diagram rendering was skipped or failed).")
		return
	}
	writeLine(f, "\nimage::"+diagramFilenamePNG+"[]")
}

func imageIsWiderThanHigh(diagramFilenamePNG string) bool {
	/* #nosec diagramFilenamePNG is not tainted (see caller restricting it to image files of model folder only) */
	imagePath, err := os.Open(diagramFilenamePNG)
	if err != nil {
		log.Println("error opening image file:", err)
		return false
	}
	defer func() { _ = imagePath.Close() }()
	srcImage, _, decodeError := image.Decode(imagePath)
	if decodeError != nil || srcImage == nil {
		return false
	}
	srcDimensions := srcImage.Bounds()
	// wider than high?
	muchWiderThanHigh := srcDimensions.Dx() > int(float64(srcDimensions.Dy())*1.25)
	return muchWiderThanHigh
}

func (adoc adocReport) writeDataFlowDiagram(diagramFilenamePNG string) error {
	filename := "060_DataFlowDiagram.adoc"
	dfd, err := os.Create(filepath.Join(adoc.targetDirectory, filename))
	defer func() { _ = dfd.Close() }()
	if err != nil {
		return err
	}
	adocDfdFilename := filepath.Join(adoc.imagesDir, "data-flow-diagram.png")
	if !fileExists(diagramFilenamePNG) {
		// diagram rendering is optional (e.g. graphviz "dot" may be missing):
		// keep the chapter but note the missing diagram instead of failing the report
		adoc.writeMainLine("<<<")
		adoc.writeMainLine("include::" + filename + "[leveloffset=+1]")
		adoc.dataFlowDiagram(dfd, "")
		return nil
	}
	err = copyFile(diagramFilenamePNG, adocDfdFilename)
	if err != nil {
		return fmt.Errorf("could not copy file: »%s« to »%s«: %w", diagramFilenamePNG, adocDfdFilename, err)
	}

	landScape := imageIsWiderThanHigh(adocDfdFilename)
	if landScape {
		adoc.writeMainLine("[page-layout=landscape]")
	}
	adoc.writeMainLine("<<<")
	adoc.writeMainLine("include::" + filename + "[leveloffset=+1]")

	adoc.dataFlowDiagram(dfd, "images/data-flow-diagram.png")
	if landScape {
		adoc.writeMainLine("[page-layout=portrait]")
	}
	return nil
}

func (adoc adocReport) dataRiskMapping(f *os.File, diagramFilenamePNG string) {
	writeLine(f, "= Data Mapping")

	writeLine(f, `
The following diagram was generated by Threagile based on the model input and gives a high-level distribution of
data assets across technical assets. The color matches the identified data breach probability and risk level (see
the "Data Breach Probabilities" chapter for more details). A solid line stands for _data is stored by the asset_
and a dashed one means _data is processed by the asset_. For a full high-resolution version of this diagram please
refer to the PNG image file alongside this report.`)
	if diagramFilenamePNG == "" {
		writeLine(f, "\nThe diagram image file is not available (e.g. because diagram rendering was skipped or failed).")
		return
	}
	writeLine(f, "\nimage::"+diagramFilenamePNG+"[]")
}

func (adoc adocReport) writeDataRiskMapping(dataAssetDiagramFilenamePNG string) error {
	filename := "130_DataRiskMapping.adoc"
	f, err := os.Create(filepath.Join(adoc.targetDirectory, filename))
	defer func() { _ = f.Close() }()
	if err != nil {
		return err
	}
	adocDataRiskMappingFilename := filepath.Join(adoc.imagesDir, "data-asset-diagram.png")
	if !fileExists(dataAssetDiagramFilenamePNG) {
		// diagram rendering is optional (e.g. graphviz "dot" may be missing):
		// keep the chapter but note the missing diagram instead of failing the report
		adoc.writeMainLine("<<<")
		adoc.writeMainLine("include::" + filename + "[leveloffset=+1]")
		adoc.dataRiskMapping(f, "")
		return nil
	}
	err = copyFile(dataAssetDiagramFilenamePNG, adocDataRiskMappingFilename)
	if err != nil {
		return fmt.Errorf("could not copy file: »%s« to »%s«: %w", dataAssetDiagramFilenamePNG, adocDataRiskMappingFilename, err)
	}

	landScape := imageIsWiderThanHigh(adocDataRiskMappingFilename)
	if landScape {
		adoc.writeMainLine("[page-layout=landscape]")
	}
	adoc.writeMainLine("<<<")
	adoc.writeMainLine("include::" + filename + "[leveloffset=+1]")

	adoc.dataRiskMapping(f, "images/data-asset-diagram.png")
	if landScape {
		adoc.writeMainLine("[page-layout=portrait]")
	}
	return nil
}
