// Package report provides report rendering functions.
// This file adds a Markdown export (H.2) for CI-friendly threat model reports.
package report

import (
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/threagile/threagile/pkg/types"
)

// MarkdownReport generates a GitHub-Flavored Markdown threat model report.
// The output is suitable for committing to the repository and rendering inline in PR reviews.
func MarkdownReport(model *types.Model) string {
	var b strings.Builder

	b.WriteString("# Threat Model Report\n\n")
	fmt.Fprintf(&b, "**Model:** %s  \n", model.Title)
	fmt.Fprintf(&b, "**Generated:** %s  \n", time.Now().UTC().Format("2006-01-02 15:04 UTC"))
	if model.Author != nil && model.Author.Name != "" {
		fmt.Fprintf(&b, "**Author:** %s  \n", model.Author.Name)
	}
	b.WriteString("\n---\n\n")

	// Summary table
	risks := collectRisks(model)
	if len(risks) > 0 {
		byCritical := countBySeverity(risks, types.CriticalSeverity)
		byHigh := countBySeverity(risks, types.HighSeverity)
		byMedium := countBySeverity(risks, types.MediumSeverity)
		byLow := countBySeverity(risks, types.LowSeverity)
		byElevated := countBySeverity(risks, types.ElevatedSeverity)

		b.WriteString("## Summary\n\n")
		b.WriteString("| Severity | Count |\n|---|---|\n")
		if byCritical > 0 {
			fmt.Fprintf(&b, "| 🔴 Critical | %d |\n", byCritical)
		}
		if byHigh > 0 {
			fmt.Fprintf(&b, "| 🟠 High | %d |\n", byHigh)
		}
		if byElevated > 0 {
			fmt.Fprintf(&b, "| 🟡 Elevated | %d |\n", byElevated)
		}
		if byMedium > 0 {
			fmt.Fprintf(&b, "| 🔵 Medium | %d |\n", byMedium)
		}
		if byLow > 0 {
			fmt.Fprintf(&b, "| ⚪ Low | %d |\n", byLow)
		}
		fmt.Fprintf(&b, "| **Total** | **%d** |\n\n", len(risks))
	}

	// Findings by severity
	b.WriteString("## Findings\n\n")
	if len(risks) == 0 {
		b.WriteString("*No findings generated.*\n\n")
	} else {
		sortedRisks := sortRisksBySeverity(risks)
		for _, r := range sortedRisks {
			sev := strings.ToUpper(r.Severity.String())
			fmt.Fprintf(&b, "### [%s] %s\n\n", sev, stripHTML(r.Title))
			fmt.Fprintf(&b, "- **ID:** `%s`\n", r.SyntheticId)
			fmt.Fprintf(&b, "- **Category:** `%s`\n", r.CategoryId)
			fmt.Fprintf(&b, "- **Impact:** %s\n", r.ExploitationImpact.String())
			fmt.Fprintf(&b, "- **Likelihood:** %s\n", r.ExploitationLikelihood.String())
			if r.MostRelevantTechnicalAssetId != "" {
				if asset, ok := model.TechnicalAssets[r.MostRelevantTechnicalAssetId]; ok {
					fmt.Fprintf(&b, "- **Asset:** %s\n", asset.Title)
				}
			}
			if len(r.DataBreachTechnicalAssetIDs) > 0 {
				assetNames := make([]string, 0, len(r.DataBreachTechnicalAssetIDs))
				for _, id := range r.DataBreachTechnicalAssetIDs {
					if a, ok := model.TechnicalAssets[id]; ok {
						assetNames = append(assetNames, a.Title)
					}
				}
				if len(assetNames) > 0 {
					fmt.Fprintf(&b, "- **Data Breach Scope:** %s\n", strings.Join(assetNames, ", "))
				}
			}
			b.WriteString("\n")
		}
	}

	// Technical assets table
	b.WriteString("## Technical Assets\n\n")
	if len(model.TechnicalAssets) == 0 {
		b.WriteString("*No technical assets defined.*\n\n")
	} else {
		b.WriteString("| Asset | Type | Internet | Confidentiality | Integrity | Availability |\n")
		b.WriteString("|---|---|---|---|---|---|\n")
		assetList := sortedAssets(model)
		for _, a := range assetList {
			internet := "No"
			if a.Internet {
				internet = "**Yes**"
			}
			fmt.Fprintf(&b, "| %s | %s | %s | %s | %s | %s |\n",
				a.Title, a.Type.String(), internet,
				a.Confidentiality.String(), a.Integrity.String(), a.Availability.String())
		}
		b.WriteString("\n")
	}

	// Data assets table
	if len(model.DataAssets) > 0 {
		b.WriteString("## Data Assets\n\n")
		b.WriteString("| Asset | Confidentiality | PII |\n|---|---|---|\n")
		for _, da := range sortedDataAssets(model) {
			pii := "No"
			if da.HasPii || len(da.PiiCategories) > 0 {
				pii = "**Yes**"
			}
			fmt.Fprintf(&b, "| %s | %s | %s |\n", da.Title, da.Confidentiality.String(), pii)
		}
		b.WriteString("\n")
	}

	b.WriteString("---\n")
	b.WriteString("*Generated by [threagile](https://github.com/threagile/threagile)*\n")
	return b.String()
}

func collectRisks(model *types.Model) []*types.Risk {
	var risks []*types.Risk
	for _, r := range model.GeneratedRisksBySyntheticId {
		risks = append(risks, r)
	}
	return risks
}

func countBySeverity(risks []*types.Risk, sev types.RiskSeverity) int {
	n := 0
	for _, r := range risks {
		if r.Severity == sev {
			n++
		}
	}
	return n
}

func sortRisksBySeverity(risks []*types.Risk) []*types.Risk {
	out := make([]*types.Risk, len(risks))
	copy(out, risks)
	sort.Slice(out, func(i, j int) bool {
		if out[i].Severity != out[j].Severity {
			return out[i].Severity > out[j].Severity
		}
		return out[i].SyntheticId < out[j].SyntheticId
	})
	return out
}

func sortedAssets(model *types.Model) []*types.TechnicalAsset {
	out := make([]*types.TechnicalAsset, 0, len(model.TechnicalAssets))
	for _, a := range model.TechnicalAssets {
		out = append(out, a)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Title < out[j].Title })
	return out
}

func sortedDataAssets(model *types.Model) []*types.DataAsset {
	out := make([]*types.DataAsset, 0, len(model.DataAssets))
	for _, da := range model.DataAssets {
		out = append(out, da)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Title < out[j].Title })
	return out
}

// stripHTML removes simple HTML tags like <b> and </b> for Markdown output.
func stripHTML(s string) string {
	var result strings.Builder
	inTag := false
	for _, ch := range s {
		if ch == '<' {
			inTag = true
			continue
		}
		if ch == '>' {
			inTag = false
			continue
		}
		if !inTag {
			result.WriteRune(ch)
		}
	}
	return result.String()
}
