// Package threatdragon converts an OWASP Threat Dragon (v2) model file into a
// partial Threagile model — a fully deterministic diagram→YAML conversion (no
// AI). Actors/processes/stores become technical assets, data flows become
// communication links, and trust-boundary boxes become trust boundaries with
// membership resolved by diagram geometry (a node belongs to the smallest box
// that geometrically contains its centre).
//
//	model, err := threatdragon.Import(jsonBytes, threatdragon.ImportOptions{})
package threatdragon

import (
	"encoding/json"
	"errors"
	"fmt"
	"regexp"
	"sort"
	"strings"

	"github.com/threagile/threagile/pkg/types"
)

var nonAlnum = regexp.MustCompile(`[^a-z0-9]+`)

func toID(parts ...string) string {
	return strings.Trim(nonAlnum.ReplaceAllString(strings.ToLower(strings.Join(parts, "-")), "-"), "-")
}

// ImportOptions controls import behaviour.
type ImportOptions struct {
	// SourceLabel is appended to generated asset IDs (default "td").
	SourceLabel string
}

type datastoreNameRule struct {
	needle string
	tech   string
}

// Ordered (deterministic) classification of store nodes by name substring.
var datastoreNames = []datastoreNameRule{
	{"postgres", types.Database},
	{"mysql", types.Database},
	{"mariadb", types.Database},
	{"mongo", types.Database},
	{"redis", types.Database},
	{"memcache", types.Database},
	{"cassandra", types.Database},
	{"elasticsearch", types.SearchEngine},
	{"opensearch", types.SearchEngine},
	{"minio", types.FileServer},
	{"s3", types.FileServer},
	{"blob", types.FileServer},
	{"bucket", types.FileServer},
	{"vault", types.Vault},
	{"queue", types.MessageQueue},
	{"kafka", types.MessageQueue},
}

type node struct {
	cell    tdCell
	assetID string
}

// Import parses a Threat Dragon JSON model and returns a partial *types.Model.
func Import(data []byte, opts ImportOptions) (*types.Model, error) {
	if opts.SourceLabel == "" {
		opts.SourceLabel = "td"
	}

	var td tdModel
	if err := json.Unmarshal(data, &td); err != nil {
		return nil, fmt.Errorf("threat-dragon: failed to parse JSON: %w", err)
	}
	if len(td.Detail.Diagrams) == 0 {
		return nil, errors.New("threat-dragon: no diagrams found (is this a Threat Dragon v2 model?)")
	}

	title := td.Summary.Title
	if strings.TrimSpace(title) == "" {
		title = "Imported from Threat Dragon"
	}

	model := &types.Model{
		ThreagileVersion:   "1.0.0",
		Title:              title,
		TechnicalAssets:    make(map[string]*types.TechnicalAsset),
		TrustBoundaries:    make(map[string]*types.TrustBoundary),
		DataAssets:         make(map[string]*types.DataAsset),
		CommunicationLinks: make(map[string]*types.CommunicationLink),
		TagsAvailable:      []string{},
	}

	b := &builder{model: model, label: opts.SourceLabel, nodesByCellID: map[string]*node{}}

	// One flattened pass over every diagram's cells, sorted for determinism.
	// With multiple diagrams (pages), cell IDs are namespaced per page so a cell
	// named "api" on two pages doesn't collide (a single-page model keeps its
	// original IDs for stable output).
	multiPage := len(td.Detail.Diagrams) > 1
	var nodeCells, boundaryCells, edgeCells []tdCell
	for di, dg := range td.Detail.Diagrams {
		cells := append([]tdCell{}, dg.Cells...)
		if multiPage {
			prefix := fmt.Sprintf("d%d-", di)
			for i := range cells {
				cells[i].ID = prefix + cells[i].ID
				if cells[i].Source != nil {
					cells[i].Source.Cell = prefix + cells[i].Source.Cell
				}
				if cells[i].Target != nil {
					cells[i].Target.Cell = prefix + cells[i].Target.Cell
				}
			}
		}
		sort.SliceStable(cells, func(i, j int) bool { return cells[i].ID < cells[j].ID })
		for _, c := range cells {
			switch {
			case c.Source != nil && c.Target != nil:
				edgeCells = append(edgeCells, c)
			case isBoundaryShape(c):
				boundaryCells = append(boundaryCells, c)
			case isNodeShape(c):
				nodeCells = append(nodeCells, c)
			}
		}
	}

	for i := range nodeCells {
		b.buildNodeAsset(nodeCells[i])
	}
	for _, e := range edgeCells {
		b.buildFlowLink(e)
	}
	b.markInternetExposure(edgeCells)
	b.assignBoundaries(boundaryCells)

	if len(model.TechnicalAssets) == 0 {
		return nil, errors.New("threat-dragon: no actor/process/store nodes found in the diagram(s)")
	}

	// Generic stub data asset so the fragment validates.
	da := &types.DataAsset{
		Id:              toID("data-imported", opts.SourceLabel),
		Title:           "Imported Data (review and classify)",
		Description:     "Stub data asset generated by threat-dragon import. Review confidentiality and PII fields.",
		Confidentiality: types.Confidential,
		Integrity:       types.Critical,
		Availability:    types.Critical,
	}
	model.DataAssets[da.Id] = da

	return model, nil
}

type builder struct {
	model         *types.Model
	label         string
	nodesByCellID map[string]*node
	usedIDs       map[string]bool // guards against toID normalisation collisions
}

// uniqueID returns base, or base-2/base-3/… if base is already taken, so two
// cells whose IDs normalise identically don't overwrite each other.
func (b *builder) uniqueID(base string) string {
	if b.usedIDs == nil {
		b.usedIDs = map[string]bool{}
	}
	id := base
	for n := 2; b.usedIDs[id]; n++ {
		id = fmt.Sprintf("%s-%d", base, n)
	}
	b.usedIDs[id] = true
	return id
}

func isNodeShape(c tdCell) bool {
	switch strings.ToLower(c.Shape) {
	case "actor", "process", "store":
		return true
	}
	switch c.Data.Type {
	case "tm.Actor", "tm.Process", "tm.Store":
		return true
	}
	return false
}

func isBoundaryShape(c tdCell) bool {
	s := strings.ToLower(c.Shape)
	return strings.Contains(s, "trust-boundary") || c.Data.Type == "tm.BoundaryBox" || c.Data.IsTrustBoundary
}

func (b *builder) buildNodeAsset(c tdCell) {
	title := c.Data.Name
	if strings.TrimSpace(title) == "" {
		title = c.ID
	}
	id := b.uniqueID(toID(c.ID, b.label))

	assetType, tech := classifyNode(c)
	asset := &types.TechnicalAsset{
		Id:              id,
		Title:           title,
		Description:     c.Data.Description,
		Type:            assetType,
		Technologies:    types.TechnologyList{&types.Technology{Name: tech}},
		Machine:         types.Virtual,
		OutOfScope:      c.Data.OutOfScope,
		Internet:        assetType == types.ExternalEntity || c.Data.IsPublicNetwork,
		Encryption:      types.NoneEncryption,
		Confidentiality: types.Confidential,
		Integrity:       types.Critical,
		Availability:    types.Critical,
	}
	if assetType == types.ExternalEntity {
		asset.UsedAsClientByHuman = strings.EqualFold(c.Shape, "actor") || c.Data.Type == "tm.Actor"
	}
	b.model.TechnicalAssets[id] = asset
	b.nodesByCellID[c.ID] = &node{cell: c, assetID: id}
}

// classifyNode maps a Threat Dragon node to a Threagile asset type + technology.
func classifyNode(c tdCell) (types.TechnicalAssetType, string) {
	shape := strings.ToLower(c.Shape)
	isActor := shape == "actor" || c.Data.Type == "tm.Actor"
	isStore := shape == "store" || c.Data.Type == "tm.Store"

	switch {
	case isActor:
		return types.ExternalEntity, types.ClientSystem
	case isStore:
		name := strings.ToLower(c.Data.Name + " " + c.ID)
		for _, rule := range datastoreNames {
			if strings.Contains(name, rule.needle) {
				return types.Datastore, rule.tech
			}
		}
		return types.Datastore, types.Database
	default: // process
		if c.Data.IsWebApplication {
			return types.Process, types.WebApplication
		}
		return types.Process, types.WebServer
	}
}

func (b *builder) buildFlowLink(e tdCell) {
	src, okS := b.nodesByCellID[e.Source.Cell]
	dst, okT := b.nodesByCellID[e.Target.Cell]
	if !okS || !okT || src.assetID == dst.assetID {
		return
	}
	title := e.Data.Name
	if strings.TrimSpace(title) == "" {
		title = src.cell.ID + " → " + dst.cell.ID
	}
	linkID := toID("link", e.Source.Cell, "to", e.Target.Cell, e.ID, b.label)
	if _, exists := b.model.CommunicationLinks[linkID]; exists {
		return
	}
	protocol := protocolFor(e)
	link := &types.CommunicationLink{
		Id:             linkID,
		SourceId:       src.assetID,
		TargetId:       dst.assetID,
		Title:          title,
		Description:    e.Data.Description,
		Protocol:       protocol,
		Authentication: types.NoneAuthentication,
		Authorization:  types.NoneAuthorization,
		Usage:          types.Business,
	}
	b.model.CommunicationLinks[linkID] = link
	srcAsset := b.model.TechnicalAssets[src.assetID]
	srcAsset.CommunicationLinks = append(srcAsset.CommunicationLinks, link)
}

func protocolFor(e tdCell) types.Protocol {
	if p, err := types.ParseProtocol(strings.ToLower(strings.TrimSpace(e.Data.Protocol))); err == nil && e.Data.Protocol != "" {
		return p
	}
	if e.Data.IsEncrypted {
		return types.HTTPS
	}
	return types.HTTP
}

// markInternetExposure flags a process/store as internet-facing when it is the
// direct target of a flow originating from an external actor.
func (b *builder) markInternetExposure(edges []tdCell) {
	for _, e := range edges {
		src, okS := b.nodesByCellID[e.Source.Cell]
		dst, okT := b.nodesByCellID[e.Target.Cell]
		if !okS || !okT {
			continue
		}
		srcAsset := b.model.TechnicalAssets[src.assetID]
		if srcAsset.Type == types.ExternalEntity {
			b.model.TechnicalAssets[dst.assetID].Internet = true
		}
	}
}

// assignBoundaries places each node asset inside the SMALLEST trust-boundary box
// that geometrically contains its centre (most-specific boundary wins).
func (b *builder) assignBoundaries(boundaries []tdCell) {
	type box struct {
		cell tdCell
		area float64
		id   string
	}
	var boxes []box
	for _, bc := range boundaries {
		if bc.Position == nil || bc.Size == nil {
			continue
		}
		boxes = append(boxes, box{cell: bc, area: bc.Size.Width * bc.Size.Height, id: b.uniqueID(toID("boundary", bc.ID, b.label))})
	}
	// Smallest box first so the first containing match is the most specific.
	sort.SliceStable(boxes, func(i, j int) bool { return boxes[i].area < boxes[j].area })

	inside := map[string][]string{} // boundary id -> asset ids
	for _, n := range b.sortedNodes() {
		if n.cell.Position == nil || n.cell.Size == nil {
			continue
		}
		cx := n.cell.Position.X + n.cell.Size.Width/2
		cy := n.cell.Position.Y + n.cell.Size.Height/2
		for _, bx := range boxes {
			p, s := bx.cell.Position, bx.cell.Size
			if cx >= p.X && cx <= p.X+s.Width && cy >= p.Y && cy <= p.Y+s.Height {
				inside[bx.id] = append(inside[bx.id], n.assetID)
				break
			}
		}
	}

	for _, bx := range boxes {
		ids := inside[bx.id]
		if len(ids) == 0 {
			continue
		}
		sort.Strings(ids)
		title := bx.cell.Data.Name
		if strings.TrimSpace(title) == "" {
			title = bx.cell.ID
		}
		boundaryType := types.NetworkVirtualLAN
		if bx.cell.Data.IsPublicNetwork || strings.Contains(strings.ToLower(title+" "+bx.cell.Data.Description), "internet") ||
			strings.Contains(strings.ToLower(title), "untrusted") {
			boundaryType = types.NetworkOnPrem
		}
		b.model.TrustBoundaries[bx.id] = &types.TrustBoundary{
			Id:                    bx.id,
			Title:                 title,
			Description:           bx.cell.Data.Description,
			Type:                  boundaryType,
			TechnicalAssetsInside: ids,
		}
	}
}

func (b *builder) sortedNodes() []*node {
	out := make([]*node, 0, len(b.nodesByCellID))
	for _, n := range b.nodesByCellID {
		out = append(out, n)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].assetID < out[j].assetID })
	return out
}
