// Package compose converts a docker-compose file into a partial Threagile model:
// services become technical assets (datastores detected from the image),
// published ports mark internet exposure, depends_on becomes communication links,
// networks become trust boundaries, and secret-looking environment variables
// produce an application-secrets data asset.
//
//	model, err := compose.Import(composeYAML, compose.ImportOptions{})
package compose

import (
	"errors"
	"fmt"
	"regexp"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/threagile/threagile/pkg/types"
)

var nonAlnum = regexp.MustCompile(`[^a-z0-9]+`)

func toID(parts ...string) string {
	return strings.Trim(nonAlnum.ReplaceAllString(strings.ToLower(strings.Join(parts, "-")), "-"), "-")
}

// ImportOptions controls import behaviour.
type ImportOptions struct {
	// SourceLabel is appended to generated asset IDs (default "compose").
	SourceLabel string
}

type datastoreImageRule struct {
	needle string
	tech   string
}

// Ordered (not a map) so classification is deterministic when an image name
// contains more than one needle.
var knownDatastoreImages = []datastoreImageRule{
	{"postgres", types.Database},
	{"mysql", types.Database},
	{"mariadb", types.Database},
	{"mongo", types.Database},
	{"redis", types.Database},
	{"memcached", types.Database},
	{"cassandra", types.Database},
	{"cockroach", types.Database},
	{"elasticsearch", types.SearchEngine},
	{"opensearch", types.SearchEngine},
	{"rabbitmq", types.MessageQueue},
	{"kafka", types.MessageQueue},
	{"nats", types.MessageQueue},
	{"minio", types.FileServer},
	{"nginx", types.ReverseProxy},
	{"traefik", types.ReverseProxy},
	{"haproxy", types.LoadBalancer},
	{"vault", types.Vault},
}

var secretEnvKey = regexp.MustCompile(`(?i)(secret|password|passwd|token|api[_-]?key|access[_-]?key|private[_-]?key)`)

// Import parses a docker-compose YAML document and returns a partial *types.Model.
func Import(data []byte, opts ImportOptions) (*types.Model, error) {
	if opts.SourceLabel == "" {
		opts.SourceLabel = "compose"
	}

	var cf composeFile
	if err := yaml.Unmarshal(data, &cf); err != nil {
		return nil, fmt.Errorf("compose: failed to parse YAML: %w", err)
	}
	if len(cf.Services) == 0 {
		return nil, errors.New("compose: no services found (is this a docker-compose file?)")
	}

	model := &types.Model{
		ThreagileVersion:   "1.0.0",
		Title:              "Imported from docker-compose",
		TechnicalAssets:    make(map[string]*types.TechnicalAsset),
		TrustBoundaries:    make(map[string]*types.TrustBoundary),
		DataAssets:         make(map[string]*types.DataAsset),
		CommunicationLinks: make(map[string]*types.CommunicationLink),
		TagsAvailable:      []string{},
	}

	// First pass: one technical asset per service.
	serviceNames := sortedKeys(cf.Services)

	// Pre-compute a stable, collision-free asset ID per service name, so two
	// services whose names normalise to the same ID (e.g. "svc_a"/"svc-a") don't
	// silently overwrite each other.
	svcIDs := uniqueServiceIDs(serviceNames, opts.SourceLabel)
	assetID := func(svc string) string { return svcIDs[svc] }
	hasSecrets := false
	for _, name := range serviceNames {
		svc := cf.Services[name]
		asset := buildServiceAsset(name, svc, assetID(name))
		model.TechnicalAssets[asset.Id] = asset
		if hasSecretEnv(svc) {
			hasSecrets = true
		}
	}

	// Application-secrets data asset if any service carries secret-like env vars.
	if hasSecrets {
		da := &types.DataAsset{
			Id:              toID("application-secrets", opts.SourceLabel),
			Title:           "Application Secrets",
			Description:     "Secret-like environment variables (passwords/tokens/keys) found in compose services. Review and move to a secret store.",
			Confidentiality: types.StrictlyConfidential,
			Integrity:       types.Critical,
			Availability:    types.Important,
			Tags:            []string{"credential"},
		}
		model.DataAssets[da.Id] = da
		for _, name := range serviceNames {
			if hasSecretEnv(cf.Services[name]) {
				a := model.TechnicalAssets[assetID(name)]
				a.DataAssetsProcessed = appendUnique(a.DataAssetsProcessed, da.Id)
			}
		}
	} else {
		// Generic stub so the fragment validates.
		da := &types.DataAsset{
			Id:              toID("data-imported", opts.SourceLabel),
			Title:           "Imported Data (review and classify)",
			Description:     "Stub data asset generated by compose import.",
			Confidentiality: types.Confidential,
			Integrity:       types.Critical,
			Availability:    types.Critical,
		}
		model.DataAssets[da.Id] = da
	}

	// Second pass: depends_on -> communication links (service -> dependency).
	for _, name := range serviceNames {
		svc := cf.Services[name]
		src := model.TechnicalAssets[assetID(name)]
		for _, dep := range dependsOnNames(svc.DependsOn) {
			depID := assetID(dep)
			if _, ok := model.TechnicalAssets[depID]; !ok {
				continue
			}
			linkID := toID("link", name, "to", dep, opts.SourceLabel)
			link := &types.CommunicationLink{
				Id:             linkID,
				SourceId:       src.Id,
				TargetId:       depID,
				Title:          name + " → " + dep,
				Description:    "depends_on " + dep,
				Protocol:       types.HTTPS,
				Authentication: types.NoneAuthentication,
				Authorization:  types.NoneAuthorization,
				Usage:          types.Business,
			}
			model.CommunicationLinks[linkID] = link
			src.CommunicationLinks = append(src.CommunicationLinks, link)
		}
	}

	// Internet exposure: services with published host ports + a shared client link.
	for _, name := range serviceNames {
		if !hasPublishedPorts(cf.Services[name]) {
			continue
		}
		target := model.TechnicalAssets[assetID(name)]
		target.Internet = true
		client := ensureClient(model, opts.SourceLabel)
		linkID := toID("link", "internet", "to", name, opts.SourceLabel)
		link := &types.CommunicationLink{
			Id:             linkID,
			SourceId:       client.Id,
			TargetId:       target.Id,
			Title:          "Published ports → " + name,
			Description:    "Host-published docker-compose ports",
			Protocol:       types.HTTPS,
			Authentication: types.NoneAuthentication,
			Authorization:  types.NoneAuthorization,
			Usage:          types.Business,
		}
		model.CommunicationLinks[linkID] = link
		client.CommunicationLinks = append(client.CommunicationLinks, link)
	}

	// Networks -> trust boundaries (each service in the first network it joins).
	assignNetworkBoundaries(model, cf, svcIDs, opts.SourceLabel)

	// Declare every tag any asset/data asset uses (e.g. the review-* security
	// tags) so the emitted model passes tag-reference validation.
	model.TagsAvailable = collectTags(model)

	return model, nil
}

// collectTags returns the sorted, de-duplicated set of tags referenced by the
// model's technical and data assets.
func collectTags(model *types.Model) []string {
	seen := map[string]bool{}
	for _, ta := range model.TechnicalAssets {
		for _, t := range ta.Tags {
			seen[t] = true
		}
	}
	for _, da := range model.DataAssets {
		for _, t := range da.Tags {
			seen[t] = true
		}
	}
	out := make([]string, 0, len(seen))
	for t := range seen {
		out = append(out, t)
	}
	sort.Strings(out)
	return out
}

// uniqueServiceIDs assigns each service name a stable, collision-free asset ID.
// names must be sorted for deterministic disambiguation.
func uniqueServiceIDs(names []string, label string) map[string]string {
	used := map[string]bool{}
	out := make(map[string]string, len(names))
	for _, n := range names {
		base := toID(n, label)
		id := base
		for i := 2; used[id]; i++ {
			id = fmt.Sprintf("%s-%d", base, i)
		}
		used[id] = true
		out[n] = id
	}
	return out
}

func buildServiceAsset(name string, svc composeService, id string) *types.TechnicalAsset {
	tech, assetType := classifyService(svc)
	custom := hasBuild(svc.Build)

	desc := "Imported from docker-compose service " + name
	if svc.Image != "" {
		desc += " (image: " + svc.Image + ")"
	} else if custom {
		desc += " (locally built)"
	}

	return &types.TechnicalAsset{
		Id:                   id,
		Title:                name,
		Description:          desc,
		Type:                 assetType,
		Technologies:         types.TechnologyList{&types.Technology{Name: tech}},
		Machine:              types.Container,
		CustomDevelopedParts: custom,
		Encryption:           types.NoneEncryption,
		Confidentiality:      types.Confidential,
		Integrity:            types.Critical,
		Availability:         types.Critical,
		Tags:                 securityReviewTags(svc),
	}
}

// dangerousCaps are Linux capabilities that materially weaken container
// isolation and warrant a manual review when added.
var dangerousCaps = map[string]bool{
	"ALL": true, "SYS_ADMIN": true, "NET_ADMIN": true, "SYS_PTRACE": true,
	"SYS_MODULE": true, "DAC_READ_SEARCH": true, "NET_RAW": true,
}

// securityReviewTags derives deterministic review tags from a compose service's
// security-relevant settings, so the highest-risk misconfigurations surface as
// findings in the imported model instead of being silently lost. All tags are
// prefixed "review-".
func securityReviewTags(svc composeService) []string {
	var tags []string
	if svc.Privileged {
		tags = append(tags, "review-privileged")
	}
	if strings.EqualFold(strings.TrimSpace(svc.NetworkMode), "host") {
		tags = append(tags, "review-host-network")
	}
	for _, v := range svc.Volumes {
		if strings.Contains(v, "/var/run/docker.sock") {
			tags = append(tags, "review-docker-socket-mount")
			break
		}
	}
	for _, c := range svc.CapAdd {
		if dangerousCaps[strings.ToUpper(strings.TrimSpace(c))] {
			tags = append(tags, "review-added-capabilities")
			break
		}
	}
	if mutableImageTag(svc.Image) {
		tags = append(tags, "review-mutable-image-tag")
	}
	return tags
}

// mutableImageTag reports whether an image reference is untagged or pinned to a
// moving tag (":latest"), which makes the deployed artifact non-reproducible.
func mutableImageTag(image string) bool {
	image = strings.TrimSpace(image)
	if image == "" {
		return false // locally built; no upstream image tag to pin
	}
	if i := strings.LastIndex(image, "@"); i >= 0 {
		return false // digest-pinned -> immutable
	}
	namePart := image
	if slash := strings.LastIndex(image, "/"); slash >= 0 {
		namePart = image[slash+1:]
	}
	colon := strings.LastIndex(namePart, ":")
	if colon < 0 {
		return true // untagged -> implicitly :latest
	}
	return strings.EqualFold(namePart[colon+1:], "latest")
}

func classifyService(svc composeService) (string, types.TechnicalAssetType) {
	img := strings.ToLower(svc.Image)
	for _, rule := range knownDatastoreImages {
		if strings.Contains(img, rule.needle) {
			switch rule.tech {
			case types.Database, types.SearchEngine, types.FileServer:
				return rule.tech, types.Datastore
			default:
				return rule.tech, types.Process
			}
		}
	}
	return types.WebServer, types.Process
}

func ensureClient(model *types.Model, label string) *types.TechnicalAsset {
	// "external-" prefix keeps this synthetic asset from colliding with a service
	// that happens to be named "internet-client".
	id := toID("external-internet-client", label)
	if a, ok := model.TechnicalAssets[id]; ok {
		return a
	}
	a := &types.TechnicalAsset{
		Id:              id,
		Title:           "Internet client",
		Description:     "External traffic source generated from host-published compose ports",
		Type:            types.ExternalEntity,
		Technologies:    types.TechnologyList{&types.Technology{Name: types.ClientSystem}},
		Internet:        true,
		Confidentiality: types.Public,
		Integrity:       types.Operational,
		Availability:    types.Operational,
	}
	model.TechnicalAssets[id] = a
	return a
}

func assignNetworkBoundaries(model *types.Model, cf composeFile, svcIDs map[string]string, label string) {
	byNetwork := map[string][]string{}
	for _, name := range sortedKeys(cf.Services) {
		nets := networkNames(cf.Services[name].Networks)
		if len(nets) == 0 {
			// Compose puts services with no explicit `networks:` on an implicit
			// "default" network — model it so they aren't left outside any
			// trust boundary (which would distort segmentation analysis).
			byNetwork["default"] = append(byNetwork["default"], svcIDs[name])
			continue
		}
		// Place the service in the first network it joins (an asset belongs to one
		// boundary); sort for determinism.
		sort.Strings(nets)
		byNetwork[nets[0]] = append(byNetwork[nets[0]], svcIDs[name])
	}
	for net, assetIDs := range byNetwork {
		sort.Strings(assetIDs)
		tbType := types.NetworkVirtualLAN
		if cfg, ok := cf.Networks[net]; ok && cfg.Internal {
			tbType = types.NetworkCloudSecurityGroup // internal: true -> more isolated
		}
		tbID := toID("network", net, label)
		model.TrustBoundaries[tbID] = &types.TrustBoundary{
			Id:                    tbID,
			Title:                 "Network: " + net,
			Description:           "docker-compose network " + net,
			Type:                  tbType,
			TechnicalAssetsInside: assetIDs,
		}
	}
}

// --- polymorphic field helpers -------------------------------------------------

// hasPublishedPorts reports whether the service publishes any port to a
// non-loopback host interface (i.e. is reachable beyond localhost). A bare
// container port binds to a random host port on all interfaces (published), but
// a binding to 127.0.0.1 / ::1 / localhost is dev-only and must NOT be treated as
// internet exposure. `expose:` is container-internal and never counts.
func hasPublishedPorts(svc composeService) bool {
	for i := range svc.Ports {
		n := &svc.Ports[i]
		switch n.Kind {
		case yaml.ScalarNode:
			if !isLoopbackBinding(n.Value) {
				return true
			}
		case yaml.MappingNode:
			var m struct {
				HostIP string `yaml:"host_ip"`
			}
			if err := n.Decode(&m); err == nil && !isLoopbackHost(m.HostIP) {
				return true
			}
		}
	}
	return false
}

// isLoopbackBinding reports whether a short-form ports entry binds only to
// loopback, e.g. "127.0.0.1:5432:5432" or "[::1]:8080:80".
func isLoopbackBinding(spec string) bool {
	parts := strings.Split(spec, ":")
	if len(parts) < 3 {
		return false // "host:container" or bare "container" -> all interfaces
	}
	host := strings.Join(parts[:len(parts)-2], ":") // everything before host:container
	host = strings.Trim(host, "[]")
	return isLoopbackHost(host)
}

func isLoopbackHost(host string) bool {
	switch strings.ToLower(strings.TrimSpace(host)) {
	case "127.0.0.1", "::1", "localhost":
		return true
	default:
		return strings.HasPrefix(host, "127.")
	}
}

func dependsOnNames(node yaml.Node) []string { return listOrMapKeys(node) }
func networkNames(node yaml.Node) []string   { return listOrMapKeys(node) }

// listOrMapKeys returns the elements of a YAML sequence, or the keys of a YAML
// mapping (docker-compose accepts both forms for depends_on / networks).
func listOrMapKeys(node yaml.Node) []string {
	switch node.Kind {
	case yaml.SequenceNode:
		var out []string
		for _, c := range node.Content {
			if c.Kind == yaml.ScalarNode {
				out = append(out, c.Value)
			}
		}
		return out
	case yaml.MappingNode:
		var out []string
		for i := 0; i+1 < len(node.Content); i += 2 {
			out = append(out, node.Content[i].Value)
		}
		return out
	default:
		return nil
	}
}

func hasSecretEnv(svc composeService) bool {
	for _, kv := range envEntries(svc.Environment) {
		if secretEnvKey.MatchString(kv) {
			return true
		}
	}
	return false
}

// envEntries returns "KEY=VALUE" strings for both the list and map forms of
// `environment`, so secret detection inspects keys AND values consistently.
func envEntries(node yaml.Node) []string {
	switch node.Kind {
	case yaml.SequenceNode:
		var out []string
		for _, c := range node.Content {
			if c.Kind == yaml.ScalarNode {
				out = append(out, c.Value)
			}
		}
		return out
	case yaml.MappingNode:
		var out []string
		for i := 0; i+1 < len(node.Content); i += 2 {
			out = append(out, node.Content[i].Value+"="+node.Content[i+1].Value)
		}
		return out
	default:
		return nil
	}
}

// hasBuild reports whether the service has a real `build` section (a string or a
// mapping). An explicit `build: null` or absent build is not "custom developed".
func hasBuild(node yaml.Node) bool {
	switch node.Kind {
	case yaml.ScalarNode:
		return node.Tag != "!!null" && node.Value != ""
	case yaml.MappingNode, yaml.SequenceNode:
		return len(node.Content) > 0
	default:
		return false
	}
}

func sortedKeys[V any](m map[string]V) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func appendUnique(s []string, v string) []string {
	for _, x := range s {
		if x == v {
			return s
		}
	}
	return append(s, v)
}
