// Package oscal exports a threat-model analysis as a NIST OSCAL
// assessment-results document, so findings can flow into a GRC / compliance
// pipeline as machine-readable evidence instead of being re-keyed by hand.
//
// The output is deterministic (UUIDv5 IDs from stable seeds, a fixed timestamp),
// so successive runs of the same model produce byte-identical documents that
// diff cleanly in version control. No AI.
package oscal

import (
	"sort"

	"github.com/google/uuid"
	"github.com/threagile/threagile/pkg/types"
)

// oscalNamespace is a fixed UUID namespace for deterministic UUIDv5 IDs.
var oscalNamespace = uuid.MustParse("6ba7b811-9dad-11d1-80b4-00c04fd430c8")

// fixedTimestamp keeps timestamps stable for reproducible, diffable output.
const fixedTimestamp = "2020-01-01T00:00:00.000Z"

// oscalVersion is the OSCAL release this document targets.
const oscalVersion = "1.1.2"

// Document is the top-level OSCAL assessment-results wrapper.
type Document struct {
	AssessmentResults AssessmentResults `json:"assessment-results"`
}

type AssessmentResults struct {
	UUID     string        `json:"uuid"`
	Metadata Metadata      `json:"metadata"`
	ImportAP ImportAP      `json:"import-ap"`
	Results  []ResultEntry `json:"results"`
}

type Metadata struct {
	Title        string `json:"title"`
	LastModified string `json:"last-modified"`
	Version      string `json:"version"`
	OSCALVersion string `json:"oscal-version"`
	Props        []Prop `json:"props,omitempty"`
}

type ImportAP struct {
	Href string `json:"href"`
}

type ResultEntry struct {
	UUID        string    `json:"uuid"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Start       string    `json:"start"`
	Findings    []Finding `json:"findings,omitempty"`
}

type Finding struct {
	UUID        string `json:"uuid"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Props       []Prop `json:"props,omitempty"`
	Target      Target `json:"target"`
}

type Prop struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

type Target struct {
	Type     string `json:"type"`
	TargetID string `json:"target-id"`
	Status   Status `json:"status"`
}

type Status struct {
	State string `json:"state"`
}

// Build produces the OSCAL assessment-results document for an analyzed model.
//
// version and modelSHA256 are recorded in the metadata as provenance props
// ("which model, which tool version produced this evidence"). Either may be
// empty, in which case that prop is omitted. The model hash is deterministic
// for a given model file, so output stays byte-identical across runs.
func Build(model *types.Model, risks []*types.Risk, version, modelSHA256 string) *Document {
	id := func(seed string) string {
		return uuid.NewSHA1(oscalNamespace, []byte(seed)).String()
	}

	var provenance []Prop
	if version != "" {
		provenance = append(provenance, Prop{Name: "threagile-version", Value: version})
	}
	if modelSHA256 != "" {
		provenance = append(provenance, Prop{Name: "model-sha256", Value: modelSHA256})
	}

	sorted := append([]*types.Risk{}, risks...)
	sort.Slice(sorted, func(i, j int) bool {
		if sorted[i].SyntheticId != sorted[j].SyntheticId {
			return sorted[i].SyntheticId < sorted[j].SyntheticId
		}
		return sorted[i].Title < sorted[j].Title
	})

	findings := make([]Finding, 0, len(sorted))
	for _, r := range sorted {
		state := "satisfied"
		if r.RiskStatus.IsStillAtRisk() {
			state = "not-satisfied"
		}
		findings = append(findings, Finding{
			UUID:        id("finding:" + r.SyntheticId),
			Title:       r.Title,
			Description: "Severity " + r.Severity.String() + "; status " + r.RiskStatus.String() + " (synthetic id " + r.SyntheticId + ").",
			Props: []Prop{
				{Name: "severity", Value: r.Severity.String()},
				{Name: "status", Value: r.RiskStatus.String()},
			},
			Target: Target{
				Type:     "objective-id",
				TargetID: r.CategoryId,
				Status:   Status{State: state},
			},
		})
	}

	result := ResultEntry{
		UUID:        id("result:" + model.Title),
		Title:       "Threagile risk findings",
		Description: "Risks generated by threagile analysis, mapped to their risk-category objectives.",
		Start:       fixedTimestamp,
		Findings:    findings,
	}

	return &Document{
		AssessmentResults: AssessmentResults{
			UUID: id("assessment-results:" + model.Title),
			Metadata: Metadata{
				Title:        "Threat-model assessment results: " + model.Title,
				LastModified: fixedTimestamp,
				Version:      "1.0.0",
				OSCALVersion: oscalVersion,
				Props:        provenance,
			},
			ImportAP: ImportAP{Href: "#threagile-assessment-plan"},
			Results:  []ResultEntry{result},
		},
	}
}
