// Package mermaid converts a Mermaid flowchart/graph diagram (the text
// diagram format most commonly embedded in READMEs) into a partial Threagile
// model. This is the reverse direction of the existing pkg/mermaid package
// (which renders a Threagile model AS a Mermaid diagram for the `threagile
// mermaid` command) — that exporter is untouched by this package.
//
// Mermaid flowcharts carry no threat-model semantics, so — like the drawio
// importer — this conversion is deterministic but LOSSY: node shapes are
// classified by their bracket syntax and label using deterministic rules,
// every generated asset is tagged "review-mermaid", and ratings default
// conservatively for manual review. There is no AI in the loop.
//
//	model, err := mermaid.Import(mmdBytes, mermaid.ImportOptions{})
package mermaid

import (
	"bufio"
	"bytes"
	"errors"
	"fmt"
	"regexp"
	"sort"
	"strings"

	"github.com/threagile/threagile/pkg/import/mapping"
	"github.com/threagile/threagile/pkg/types"
)

var nonAlnum = regexp.MustCompile(`[^a-z0-9]+`)

func toID(parts ...string) string {
	return strings.Trim(nonAlnum.ReplaceAllString(strings.ToLower(strings.Join(parts, "-")), "-"), "-")
}

// ImportOptions controls import behaviour.
type ImportOptions struct {
	// SourceLabel is appended to generated asset IDs (default "mermaid").
	SourceLabel string

	// Mapping is an optional user-supplied mapping dictionary (P3) applied to
	// every node/edge right after it is classified, so corrections land
	// before P4 stub generation runs on the resulting model. Mermaid source
	// carries no style/color metadata, so only Mapping's label matcher will
	// ever fire here. nil means no mapping rules are applied.
	Mapping *mapping.Ruleset

	// Boundary, when set, scopes the import to only the elements inside the
	// named trust boundary's (subgraph's) subtree, skipping everything else.
	// Matched case-insensitively against the subgraph's title. See
	// docs/import-mermaid.md and pkg/import/drawio's identical flag for the
	// full rationale (100+-node diagrams producing unreviewable YAML).
	Boundary string
}

// reviewTag flags every imported asset for manual review (mermaid diagrams
// carry no threat-model semantics).
const reviewTag = "review-mermaid"

// Import parses a Mermaid flowchart/graph document and returns a partial
// *types.Model. It never panics on malformed input; unparseable lines are
// best-effort skipped.
func Import(data []byte, opts ImportOptions) (*types.Model, error) {
	if opts.SourceLabel == "" {
		opts.SourceLabel = "mermaid"
	}

	model := &types.Model{
		ThreagileVersion:   "1.0.0",
		Title:              "Imported from Mermaid",
		TechnicalAssets:    make(map[string]*types.TechnicalAsset),
		TrustBoundaries:    make(map[string]*types.TrustBoundary),
		DataAssets:         make(map[string]*types.DataAsset),
		CommunicationLinks: make(map[string]*types.CommunicationLink),
		TagsAvailable:      []string{reviewTag},
	}

	b := &builder{model: model, label: opts.SourceLabel, mapping: opts.Mapping, nodesByRef: map[string]*nodeInfo{}, boundaries: map[string]*boundaryInfo{}}

	if err := b.parse(data); err != nil {
		return nil, err
	}

	if len(model.TechnicalAssets) == 0 {
		return nil, errors.New("mermaid: no nodes could be parsed from the flowchart (expected a `flowchart`/`graph` block with node declarations and/or edges)")
	}

	b.finishBoundaries()

	if opts.Boundary != "" {
		if err := scopeToBoundary(model, opts.Boundary); err != nil {
			return nil, err
		}
		if len(model.TechnicalAssets) == 0 {
			return nil, fmt.Errorf("mermaid: trust boundary %q contains no technical assets", opts.Boundary)
		}
	}

	da := &types.DataAsset{
		Id:              toID("data-imported", opts.SourceLabel),
		Title:           "Imported Data (review and classify)",
		Description:     "Stub data asset generated by mermaid import. Review confidentiality and PII fields.",
		Confidentiality: types.Confidential,
		Integrity:       types.Critical,
		Availability:    types.Critical,
		Tags:            []string{reviewTag},
	}
	model.DataAssets[da.Id] = da

	return model, nil
}

type nodeShape int

const (
	shapeRectangle nodeShape = iota
	shapeStadium             // ([Label]) -> external-entity/user
	shapeCylinder            // [(Label)]  -> datastore
	shapeRhombus             // {Label}    -> decision, low priority process
)

type nodeInfo struct {
	ref        string // the mermaid-source node id
	assetID    string // the generated Threagile technical asset id
	boundaryID string // "" if at top level
	cachedType types.TechnicalAssetType
}

type boundaryInfo struct {
	id       string
	title    string
	parent   string // "" if top-level
	members  []string
	children []string
	seen     bool // whether this boundary has actually been opened via `subgraph`
}

type builder struct {
	model      *types.Model
	label      string
	mapping    *mapping.Ruleset
	usedIDs    map[string]bool
	nodesByRef map[string]*nodeInfo
	boundaries map[string]*boundaryInfo
	// boundaryStack holds the boundary-id nesting path while parsing subgraphs.
	boundaryStack []string
	// order preserves first-seen order for boundaries so output is deterministic
	// without depending on map iteration.
	boundaryOrder []string
}

// uniqueID returns base, or base-2/base-3/… if base is already taken, so two
// nodes whose IDs normalise identically don't overwrite each other.
func (b *builder) uniqueID(base string) string {
	if b.usedIDs == nil {
		b.usedIDs = map[string]bool{}
	}
	id := base
	for n := 2; b.usedIDs[id]; n++ {
		id = fmt.Sprintf("%s-%d", base, n)
	}
	b.usedIDs[id] = true
	return id
}

var (
	reFlowchartHeader = regexp.MustCompile(`(?i)^(flowchart|graph)\s+(TD|TB|LR|RL|BT)?\s*$`)
	reSubgraphQuoted  = regexp.MustCompile(`^subgraph\s+"([^"]*)"\s*$`)
	reSubgraphIDLabel = regexp.MustCompile(`^subgraph\s+(\S+)\s*\[\s*"?([^"\]]*)"?\s*\]\s*$`)
	reSubgraphBareID  = regexp.MustCompile(`^subgraph\s+(\S+)\s*$`)
	reEnd             = regexp.MustCompile(`^end\s*$`)

	// Arrow alternatives, longest/most specific first so "-->" isn't matched by
	// a shorter, wrong alternative.
	reEdge = regexp.MustCompile(`^(.+?)\s*(-\.->|==>|-->|---)\s*(?:\|([^|]*)\|\s*)?(.+)$`)

	reStadium = regexp.MustCompile(`^([\w.:-]+)\(\[(.*)\]\)$`)
	reCyl     = regexp.MustCompile(`^([\w.:-]+)\[\((.*)\)\]$`)
	reRhombus = regexp.MustCompile(`^([\w.:-]+)\{(.*)\}$`)
	reRect    = regexp.MustCompile(`^([\w.:-]+)\[(.*)\]$`)
	reBareID  = regexp.MustCompile(`^([\w.:-]+)$`)
)

// parse walks the document line by line. It is intentionally forgiving:
// unrecognised lines are skipped rather than treated as errors, so a
// best-effort partial parse is always possible.
func (b *builder) parse(data []byte) error {
	scanner := bufio.NewScanner(bytes.NewReader(data))
	// Guard against pathological single-line input blowing the default 64KiB
	// token buffer.
	scanner.Buffer(make([]byte, 0, 64*1024), 4*1024*1024)

	for scanner.Scan() {
		line := stripComment(scanner.Text())
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}

		switch {
		case reFlowchartHeader.MatchString(line):
			continue
		case reEnd.MatchString(line):
			b.popBoundary()
		case strings.HasPrefix(line, "subgraph"):
			b.pushBoundary(line)
		case reEdge.MatchString(line):
			b.handleEdgeLine(line)
		default:
			b.handleNodeLine(line)
		}
	}
	return scanner.Err()
}

// stripComment removes a trailing `%%` Mermaid comment, if any.
func stripComment(line string) string {
	if idx := strings.Index(line, "%%"); idx >= 0 {
		return line[:idx]
	}
	return line
}

func (b *builder) currentBoundary() string {
	if len(b.boundaryStack) == 0 {
		return ""
	}
	return b.boundaryStack[len(b.boundaryStack)-1]
}

func (b *builder) pushBoundary(line string) {
	var ref, title string
	switch {
	case reSubgraphQuoted.MatchString(line):
		m := reSubgraphQuoted.FindStringSubmatch(line)
		title = m[1]
		ref = title
	case reSubgraphIDLabel.MatchString(line):
		m := reSubgraphIDLabel.FindStringSubmatch(line)
		ref = m[1]
		title = m[2]
	case reSubgraphBareID.MatchString(line):
		m := reSubgraphBareID.FindStringSubmatch(line)
		ref = m[1]
		title = ref
	default:
		return // malformed subgraph line — skip, don't push anything
	}
	if strings.TrimSpace(title) == "" {
		title = ref
	}

	bID := b.uniqueID(toID("boundary", ref, b.label))
	parent := b.currentBoundary()
	bi := &boundaryInfo{id: bID, title: title, parent: parent, seen: true}
	b.boundaries[bID] = bi
	b.boundaryOrder = append(b.boundaryOrder, bID)
	if parent != "" {
		b.boundaries[parent].children = append(b.boundaries[parent].children, bID)
	}
	b.boundaryStack = append(b.boundaryStack, bID)
}

func (b *builder) popBoundary() {
	if len(b.boundaryStack) == 0 {
		return // stray `end` — ignore rather than error, matches drawio tolerance
	}
	b.boundaryStack = b.boundaryStack[:len(b.boundaryStack)-1]
}

// handleNodeLine parses a bare node declaration (no arrow), e.g. `API[API
// Server]` or a bare `SomeID`.
func (b *builder) handleNodeLine(line string) {
	_ = b.resolveNode(line)
}

// handleEdgeLine parses one `A --> B`, `A -->|label| B`, `A --- B`,
// `A -.->|label| B`, or `A ==>|label| B` line, creating both endpoints (with
// whatever shape syntax they carry inline) and the communication link.
func (b *builder) handleEdgeLine(line string) {
	m := reEdge.FindStringSubmatch(line)
	if m == nil {
		return
	}
	leftTok, arrow, label, rightTok := strings.TrimSpace(m[1]), m[2], strings.TrimSpace(m[3]), strings.TrimSpace(m[4])

	src := b.resolveNode(leftTok)
	dst := b.resolveNode(rightTok)
	if src == nil || dst == nil || src.assetID == dst.assetID {
		return
	}

	title := label
	if title == "" {
		title = src.ref + " -> " + dst.ref
	}
	linkID := b.uniqueID(toID("link", src.ref, "to", dst.ref, b.label))
	dotted := arrow == "-.->"

	protocol := guessProtocol(label)
	link := &types.CommunicationLink{
		Id:             linkID,
		SourceId:       src.assetID,
		TargetId:       dst.assetID,
		Title:          title,
		Description:    "Imported from mermaid flow (review protocol/auth)",
		Protocol:       protocol,
		Authentication: types.NoneAuthentication,
		Authorization:  types.NoneAuthorization,
		Usage:          types.Business,
		Tags:           []string{reviewTag},
	}
	if dotted {
		link.Tags = append(link.Tags, "mermaid-dotted-edge")
	}

	el := mapping.Element{Label: title, Edge: true}
	mapping.ApplyToCommunicationLink(b.mapping, link, el)

	if _, exists := b.model.CommunicationLinks[linkID]; exists {
		return
	}
	b.model.CommunicationLinks[linkID] = link
	srcAsset := b.model.TechnicalAssets[src.assetID]
	srcAsset.CommunicationLinks = append(srcAsset.CommunicationLinks, link)

	if src.assetType() == types.ExternalEntity {
		dstAsset := b.model.TechnicalAssets[dst.assetID]
		dstAsset.Internet = true
	}
}

func (n *nodeInfo) assetType() types.TechnicalAssetType { return n.cachedType }

// resolveNode parses a node token (bare id, or id with shape brackets),
// creating the technical asset the first time it is seen and reusing it on
// subsequent references (bare-id references inside a subgraph or on an edge
// line don't overwrite a previously-declared shape/label).
func (b *builder) resolveNode(tok string) *nodeInfo {
	tok = strings.TrimSpace(tok)
	if tok == "" {
		return nil
	}

	ref, shape, label, ok := parseNodeToken(tok)
	if !ok {
		return nil
	}

	if existing, found := b.nodesByRef[ref]; found {
		// Classification is fixed at first declaration; later references
		// (bare, or with a differing shape) only affect boundary membership.
		b.registerMembership(existing)
		return existing
	}

	if label == "" {
		label = ref
	}

	assetType, tech := classifyNode(shape, label)
	id := b.uniqueID(toID(ref, b.label))
	asset := &types.TechnicalAsset{
		Id:              id,
		Title:           label,
		Description:     "Imported from mermaid flowchart node (review classification)",
		Type:            assetType,
		Technologies:    types.TechnologyList{&types.Technology{Name: tech}},
		Machine:         types.Virtual,
		Internet:        assetType == types.ExternalEntity,
		Encryption:      types.NoneEncryption,
		Confidentiality: types.Confidential,
		Integrity:       types.Critical,
		Availability:    types.Critical,
		Tags:            []string{reviewTag},
	}
	if assetType == types.ExternalEntity {
		asset.UsedAsClientByHuman = true
	}
	mapping.ApplyToTechnicalAsset(b.mapping, asset, mapping.Element{Label: label})
	b.model.TechnicalAssets[id] = asset

	ni := &nodeInfo{ref: ref, assetID: id}
	ni.cachedType = assetType
	b.nodesByRef[ref] = ni
	b.registerMembership(ni)
	return ni
}

// registerMembership adds the node to the currently-open boundary (if any),
// once per boundary (idempotent against repeated references on multiple edge
// lines).
func (b *builder) registerMembership(n *nodeInfo) {
	cur := b.currentBoundary()
	if cur == "" {
		return
	}
	if n.boundaryID == cur {
		return
	}
	bi := b.boundaries[cur]
	for _, m := range bi.members {
		if m == n.assetID {
			return
		}
	}
	bi.members = append(bi.members, n.assetID)
	n.boundaryID = cur
}

// parseNodeToken extracts (ref, shape, label, ok) from a single node token
// such as `API[API Server]`, `User([User])`, `DB[(Postgres)]`, `X{Decide}`,
// or a bare `ID`. ok is false when the token doesn't look like a node
// reference at all (e.g. stray punctuation from a malformed line).
func parseNodeToken(tok string) (ref string, shape *nodeShape, label string, ok bool) {
	if m := reStadium.FindStringSubmatch(tok); m != nil {
		s := shapeStadium
		return m[1], &s, strings.TrimSpace(m[2]), true
	}
	if m := reCyl.FindStringSubmatch(tok); m != nil {
		s := shapeCylinder
		return m[1], &s, strings.TrimSpace(m[2]), true
	}
	if m := reRhombus.FindStringSubmatch(tok); m != nil {
		s := shapeRhombus
		return m[1], &s, strings.TrimSpace(m[2]), true
	}
	if m := reRect.FindStringSubmatch(tok); m != nil {
		s := shapeRectangle
		return m[1], &s, strings.TrimSpace(m[2]), true
	}
	if m := reBareID.FindStringSubmatch(tok); m != nil {
		return m[1], nil, "", true
	}
	return "", nil, "", false
}

// datastoreNames classifies a cylinder-shaped node's technology from
// keywords in its label, mirroring the drawio/threat-dragon importers'
// datastoreNames table for consistency across importers.
var datastoreNames = []struct{ needle, tech string }{
	{"postgres", types.Database}, {"mysql", types.Database}, {"mariadb", types.Database},
	{"mongo", types.Database}, {"redis", types.Database}, {"cassandra", types.Database},
	{"sql", types.Database}, {"database", types.Database}, {"db", types.Database},
	{"elasticsearch", types.SearchEngine}, {"opensearch", types.SearchEngine},
	{"s3", types.FileServer}, {"bucket", types.FileServer}, {"blob", types.FileServer},
	{"minio", types.FileServer}, {"storage", types.FileServer},
	{"vault", types.Vault}, {"queue", types.MessageQueue}, {"kafka", types.MessageQueue},
}

// classifyNode maps a mermaid node's shape + label to a Threagile asset type
// and technology guess.
func classifyNode(shape *nodeShape, label string) (types.TechnicalAssetType, string) {
	name := strings.ToLower(label)

	if shape != nil {
		switch *shape {
		case shapeStadium:
			return types.ExternalEntity, types.ClientSystem
		case shapeCylinder:
			for _, rule := range datastoreNames {
				if strings.Contains(name, rule.needle) {
					return types.Datastore, rule.tech
				}
			}
			return types.Datastore, types.Database
		case shapeRhombus:
			return types.Process, types.WebServer
		}
	}

	// Rectangle or bare id: fall back to label-keyword heuristics, same
	// keyword families used by the drawio importer, for cross-importer
	// classification consistency.
	switch {
	case matchesAny(name, "user", "client", "browser", "customer", "actor", "attacker", "external", "third-party", "person"):
		return types.ExternalEntity, types.ClientSystem
	case matchesAny(name, "db", "database", "store", "datastore", "postgres", "mysql", "mongo", "redis", "cache", "bucket", "s3", "queue", "sql", "minio"):
		for _, rule := range datastoreNames {
			if strings.Contains(name, rule.needle) {
				return types.Datastore, rule.tech
			}
		}
		return types.Datastore, types.Database
	default:
		return types.Process, types.WebServer
	}
}

// guessProtocol classifies a communication link's protocol from its edge
// label, defaulting to HTTPS (a conservative "assume encrypted" default
// consistent with the drawio importer) when no keyword matches.
func guessProtocol(label string) types.Protocol {
	l := strings.ToLower(label)
	switch {
	case matchesAny(l, "https", "tls", "ssl"):
		return types.HTTPS
	case matchesAny(l, "grpc"):
		return types.HTTPS
	case matchesAny(l, "http"):
		return types.HTTP
	case matchesAny(l, "ssh"):
		return types.SSH
	case matchesAny(l, "sftp"):
		return types.SFTP
	case matchesAny(l, "ftps"):
		return types.FTPS
	case matchesAny(l, "ftp"):
		return types.FTP
	case matchesAny(l, "ldaps"):
		return types.LDAPS
	case matchesAny(l, "ldap"):
		return types.LDAP
	case matchesAny(l, "smtps", "smtp+tls"):
		return types.SmtpEncrypted
	case matchesAny(l, "smtp"):
		return types.SMTP
	case matchesAny(l, "mqtt"):
		return types.MQTT
	case matchesAny(l, "kafka", "amqp", "queue", "jms"):
		return types.JMS
	case matchesAny(l, "nfs"):
		return types.NFS
	case matchesAny(l, "smb", "cifs"):
		return types.SMB
	case matchesAny(l, "sql", "postgres", "mysql", "jdbc", "odbc"):
		return types.SqlAccessProtocolEncrypted
	case matchesAny(l, "nosql", "mongo", "redis"):
		return types.NosqlAccessProtocolEncrypted
	default:
		return types.HTTPS
	}
}

func matchesAny(haystack string, needles ...string) bool {
	for _, n := range needles {
		if strings.Contains(haystack, n) {
			return true
		}
	}
	return false
}

// finishBoundaries materialises every boundary that had at least one member
// or nested child into the model's TrustBoundaries map. Empty boundaries
// (declared but never populated — e.g. a `subgraph`/`end` pair with no nodes
// inside) are dropped, mirroring the other importers' behaviour of never
// emitting empty structural noise.
func (b *builder) finishBoundaries() {
	for _, bID := range b.boundaryOrder {
		bi := b.boundaries[bID]
		if len(bi.members) == 0 && len(bi.children) == 0 {
			continue
		}
		sort.Strings(bi.members)
		sort.Strings(bi.children)
		boundaryType := types.NetworkVirtualLAN
		if matchesAny(strings.ToLower(bi.title), "internet", "untrusted", "public", "dmz") {
			boundaryType = types.NetworkOnPrem
		}
		b.model.TrustBoundaries[bID] = &types.TrustBoundary{
			Id:                    bID,
			Title:                 bi.title,
			Description:           "Imported from mermaid subgraph",
			Type:                  boundaryType,
			Tags:                  []string{reviewTag},
			TechnicalAssetsInside: bi.members,
			TrustBoundariesNested: bi.children,
		}
	}
}

// scopeToBoundary prunes model down to just the elements inside the named
// trust boundary's subtree — the mermaid counterpart of drawio's identical
// function (see pkg/import/drawio/importer.go for the full rationale).
// Matched case-insensitively against a trust boundary's Title.
func scopeToBoundary(model *types.Model, boundaryName string) error {
	var rootID string
	for id, tb := range model.TrustBoundaries {
		if strings.EqualFold(tb.Title, boundaryName) {
			rootID = id
			break
		}
	}
	if rootID == "" {
		return fmt.Errorf("mermaid: no trust boundary named %q found (case-insensitive match on the subgraph's label)", boundaryName)
	}

	keepBoundary := map[string]bool{}
	var walk func(id string)
	walk = func(id string) {
		if keepBoundary[id] {
			return
		}
		keepBoundary[id] = true
		tb, ok := model.TrustBoundaries[id]
		if !ok {
			return
		}
		for _, child := range tb.TrustBoundariesNested {
			walk(child)
		}
	}
	walk(rootID)

	keepAsset := map[string]bool{}
	for id := range keepBoundary {
		for _, assetID := range model.TrustBoundaries[id].TechnicalAssetsInside {
			keepAsset[assetID] = true
		}
	}

	for id := range model.TrustBoundaries {
		if !keepBoundary[id] {
			delete(model.TrustBoundaries, id)
		}
	}
	for id, ta := range model.TechnicalAssets {
		if !keepAsset[id] {
			delete(model.TechnicalAssets, id)
			continue
		}
		filtered := ta.CommunicationLinks[:0:0]
		for _, link := range ta.CommunicationLinks {
			if keepAsset[link.SourceId] && keepAsset[link.TargetId] {
				filtered = append(filtered, link)
			}
		}
		ta.CommunicationLinks = filtered
	}
	for id, link := range model.CommunicationLinks {
		if !keepAsset[link.SourceId] || !keepAsset[link.TargetId] {
			delete(model.CommunicationLinks, id)
		}
	}
	return nil
}
