// Package terraform converts `terraform show -json` output into a partial Threagile model.
// The generated model contains technical_assets, trust_boundaries and a stub data asset
// for every resource that Threagile understands. Unknown resource types are silently skipped.
//
// Usage:
//
//	result, err := terraform.Import(planJSON)
//	// result is a *types.Model ready to be marshalled as YAML
package terraform

import (
	"encoding/json"
	"fmt"
	"regexp"
	"strings"

	"github.com/threagile/threagile/pkg/types"
)

var nonAlnum = regexp.MustCompile(`[^a-z0-9]+`)

func toID(s string) string {
	return strings.Trim(nonAlnum.ReplaceAllString(strings.ToLower(s), "-"), "-")
}

// ImportOptions controls import behaviour.
type ImportOptions struct {
	// SourceLabel is a short label appended to generated asset IDs to distinguish
	// between multiple imported sources (e.g. "prod", "staging"). Defaults to "tf".
	SourceLabel string
}

// Import parses `terraform show -json` JSON bytes and returns a partial *types.Model.
func Import(data []byte, opts ImportOptions) (*types.Model, error) {
	if opts.SourceLabel == "" {
		opts.SourceLabel = "tf"
	}

	var show TFShow
	if err := json.Unmarshal(data, &show); err != nil {
		return nil, fmt.Errorf("terraform: failed to parse JSON: %w", err)
	}

	// Support both state files (values) and plan files (planned_values).
	var root TFModule
	switch {
	case show.Values != nil:
		root = show.Values.RootModule
	case show.PlannedValues != nil:
		root = show.PlannedValues.RootModule
	default:
		return nil, fmt.Errorf("terraform: JSON does not contain 'values' or 'planned_values'; are you passing `terraform show -json` output?")
	}

	resources := flatResources(root)

	model := &types.Model{
		ThreagileVersion: "1.0.0",
		Title:            "Imported from Terraform",
		TechnicalAssets:  make(map[string]*types.TechnicalAsset),
		TrustBoundaries:  make(map[string]*types.TrustBoundary),
		DataAssets:       make(map[string]*types.DataAsset),
		TagsAvailable:    []string{},
	}

	// Deduplicate resource addresses to handle modules that define the same resource twice.
	seen := make(map[string]bool)

	for i := range resources {
		r := &resources[i]
		if seen[r.Address] {
			continue
		}
		seen[r.Address] = true

		m := lookupMapping(r.Type)
		if m == nil {
			// Unknown resource type — skip silently
			continue
		}

		id := toID(r.Address) + "-" + opts.SourceLabel

		if m.isBoundary {
			tb := buildTrustBoundary(r, id, m)
			model.TrustBoundaries[tb.Id] = tb
			continue
		}

		asset := buildTechnicalAsset(r, id, m)
		model.TechnicalAssets[asset.Id] = asset
	}

	// Add a generic stub data asset so the model validates.
	if len(model.TechnicalAssets) > 0 {
		da := &types.DataAsset{
			Id:              "data-imported-" + opts.SourceLabel,
			Title:           "Imported Data (review and classify)",
			Description:     "Stub data asset generated by terraform import. Review confidentiality and PII fields.",
			Confidentiality: types.Confidential,
			Integrity:       types.Critical,
			Availability:    types.Critical,
		}
		model.DataAssets[da.Id] = da
	}

	return model, nil
}

func buildTechnicalAsset(r *TFResource, id string, m *resourceMapping) *types.TechnicalAsset {
	title := humanTitle(r)

	// Guess encryption from resource-specific config
	enc := guessEncryption(r, m)

	// Guess internet exposure from resource config
	internet := m.internet || guessInternet(r)

	assetType := types.Process
	if m.assetType == "datastore" {
		assetType = types.Datastore
	}

	tech := types.TechnologyList{&types.Technology{Name: m.technology}}

	tags := buildTags(r)

	return &types.TechnicalAsset{
		Id:              id,
		Title:           title,
		Description:     fmt.Sprintf("Imported from Terraform resource %s (%s)", r.Address, r.Type),
		Type:            assetType,
		Technologies:    tech,
		Internet:        internet,
		Encryption:      enc,
		Confidentiality: types.Confidential,
		Integrity:       types.Critical,
		Availability:    types.Critical,
		Tags:            tags,
	}
}

func buildTrustBoundary(r *TFResource, id string, m *resourceMapping) *types.TrustBoundary {
	title := humanTitle(r)

	tbType, _ := types.ParseTrustBoundary(m.boundaryKind)

	return &types.TrustBoundary{
		Id:          id,
		Title:       title,
		Description: fmt.Sprintf("Imported from Terraform resource %s (%s)", r.Address, r.Type),
		Type:        tbType,
	}
}

// humanTitle produces a readable title from the resource address and values.
func humanTitle(r *TFResource) string {
	// Prefer explicit name/id fields from the values map
	for _, key := range []string{"name", "bucket", "function_name", "cluster_identifier", "identifier", "table_name", "queue_name", "topic_name"} {
		if v := strVal(r.Values, key); v != "" {
			return v
		}
	}
	// Fall back to resource name portion of address (last segment after last .)
	parts := strings.Split(r.Address, ".")
	if len(parts) >= 2 {
		return parts[len(parts)-1]
	}
	return r.Address
}

// guessEncryption inspects known encryption-related attributes.
func guessEncryption(r *TFResource, m *resourceMapping) types.EncryptionStyle {
	// If the mapping already has a forced encryption, use it as default.
	base := types.NoneEncryption
	if m.encryption == "transparent" {
		base = types.Transparent
	}

	v := r.Values

	// AWS S3: server_side_encryption_configuration
	if encConf, ok := v["server_side_encryption_configuration"]; ok && encConf != nil {
		if arr, ok := encConf.([]any); ok && len(arr) > 0 {
			return types.Transparent
		}
	}

	// AWS RDS: storage_encrypted
	if boolVal(v, "storage_encrypted") {
		return types.Transparent
	}

	// AWS DynamoDB: server_side_encryption
	if sse, ok := v["server_side_encryption"]; ok && sse != nil {
		if arr, ok := sse.([]any); ok && len(arr) > 0 {
			if m0, ok := arr[0].(map[string]any); ok {
				if boolVal(m0, "enabled") {
					return types.Transparent
				}
			}
		}
	}

	// Generic: look for any attribute containing "encrypt" with a true/enabled value
	for k, val := range v {
		if strings.Contains(k, "encrypt") {
			if b, ok := val.(bool); ok && b {
				return types.Transparent
			}
			if s, ok := val.(string); ok && (s == "true" || s == "enabled" || s == "AES256" || s == "aws:kms") {
				return types.Transparent
			}
		}
	}

	return base
}

// guessInternet checks whether the resource has public/internet-facing attributes.
func guessInternet(r *TFResource) bool {
	v := r.Values

	// Explicit public attributes
	for _, key := range []string{"publicly_accessible", "public_access", "public_ip_enabled"} {
		if boolVal(v, key) {
			return true
		}
	}

	// S3: bucket_acl / acl
	for _, key := range []string{"acl", "bucket_acl"} {
		if s := strVal(v, key); s == "public-read" || s == "public-read-write" || s == "authenticated-read" {
			return true
		}
	}

	// S3 public access block: if any block_public_acls=false etc.
	if pab, ok := v["block_public_acls"]; ok {
		if b, ok := pab.(bool); ok && !b {
			return true
		}
	}

	return false
}

// buildTags generates tag hints from the resource.
func buildTags(r *TFResource) []string {
	tags := []string{}

	v := r.Values

	// Detect encryption → has-encryption-at-rest
	if enc := guessEncryption(r, &resourceMapping{}); enc != types.NoneEncryption {
		tags = append(tags, "has-encryption-at-rest")
	}

	// AWS Lambda: dead_letter_config
	if dlc, ok := v["dead_letter_config"]; ok && dlc != nil {
		if arr, ok := dlc.([]any); ok && len(arr) > 0 {
			tags = append(tags, "has-dlq")
		}
	}

	// Versioning
	for _, key := range []string{"versioning", "versioning_enabled"} {
		if ver, ok := v[key]; ok && ver != nil {
			if arr, ok := ver.([]any); ok && len(arr) > 0 {
				if m0, ok := arr[0].(map[string]any); ok {
					if boolVal(m0, "enabled") {
						tags = append(tags, "has-versioning")
					}
				}
			}
		}
	}

	// Automated backup (RDS)
	if bv, ok := v["backup_retention_period"]; ok {
		if n, ok := bv.(float64); ok && n > 0 {
			tags = append(tags, "has-automated-backup")
		}
	}

	return tags
}
