package threagile

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gopkg.in/yaml.v3"
)

// TestFmtPreservesScaffoldComments locks in fmt's current behavior: the
// yaml.Node round-trip it performs keeps comments attached, so a scaffold
// fragment (docs/import-scaffold.md) can be formatted mid-review without
// losing its TODO(review) annotations. If fmt ever switches to a
// comment-stripping normalisation, this test — and the note in
// docs/import-scaffold.md — must change together.
func TestFmtPreservesScaffoldComments(t *testing.T) {
	scaffolded := `# Threagile scaffold generated by ` + "`threagile import mermaid`" + ` (deterministic, no AI).
title: Imported from Mermaid
technical_assets:
    Web Frontend:
        id: web-mermaid
        # TODO(review): asset type inferred from diagram shape/label — confirm this matches the real asset (external-entity/process/datastore)
        type: process
        tags:
            - review-mermaid
        # TODO(review): encryption defaulted conservatively — set the actual encryption in use
        encryption: none
`

	var doc yaml.Node
	require.NoError(t, yaml.Unmarshal([]byte(scaffolded), &doc))
	formatted, err := yaml.Marshal(&doc)
	require.NoError(t, err)

	assert.Equal(t, strings.Count(scaffolded, "TODO(review)"), strings.Count(string(formatted), "TODO(review)"),
		"fmt's yaml.Node round-trip must preserve every TODO(review) scaffold comment")
	assert.Contains(t, string(formatted), "# Threagile scaffold generated by",
		"header comments must survive the round-trip too")

	// The comment must still annotate the field it was written for, not
	// merely appear somewhere in the file.
	lines := strings.Split(string(formatted), "\n")
	for i, line := range lines {
		if strings.Contains(line, "asset type inferred") {
			require.Less(t, i+1, len(lines))
			assert.Contains(t, lines[i+1], "type:",
				"the type TODO(review) comment must stay attached to the type field")
		}
	}
}
