package threagile

import (
	"fmt"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/threagile/threagile/pkg/types"
)

// This file implements the "scaffold" output mode shared by the
// diagram-derived importers (drawio, threat-dragon, otm) — see improvement.md
// P2. Diagrams carry no threat-model semantics, so every classification these
// importers make (asset type, technology, machine, encryption, CIA ratings,
// trust-boundary type) is a heuristic guess. Plain `yaml.Marshal` of the
// converted model would bury that fact; scaffold mode instead re-parses the
// marshalled YAML into a *yaml.Node tree and attaches a
// "TODO(review): ..." head-comment to every field a diagram importer only
// ever guesses at, plus a file-header block summarising what was generated.
//
// IaC-derived importers (terraform/openapi/kubernetes/compose) are not
// scaffolded: their fields come from real configuration, not shape/label
// heuristics, so plain output stays accurate.

// scaffoldFieldReasons maps a technical-asset field name to the reason it is
// always a heuristic guess for a diagram importer.
var scaffoldTechnicalAssetReasons = map[string]string{
	"type":            "asset type inferred from diagram shape/label — confirm this matches the real asset (external-entity/process/datastore)",
	"technology":      "technology guessed from the shape name/type keywords — set the actual technology",
	"technologies":    "technology guessed from the shape name/type keywords — set the actual technology",
	"machine":         "machine defaulted to a conservative guess — confirm the actual deployment (physical/virtual/container/serverless)",
	"encryption":      "encryption defaulted conservatively — set the actual encryption in use",
	"confidentiality": "CIA rating defaulted conservatively — confirm against the real data classification",
	"integrity":       "CIA rating defaulted conservatively — confirm against the real data classification",
	"availability":    "CIA rating defaulted conservatively — confirm against the real data classification",
}

// scaffoldDataAssetReasons maps a data-asset field name to its reason.
var scaffoldDataAssetReasons = map[string]string{
	"confidentiality": "CIA rating defaulted conservatively — confirm against the real data classification",
	"integrity":       "CIA rating defaulted conservatively — confirm against the real data classification",
	"availability":    "CIA rating defaulted conservatively — confirm against the real data classification",
}

// scaffoldTrustBoundaryReasons maps a trust-boundary field name to its reason.
var scaffoldTrustBoundaryReasons = map[string]string{
	"type": "trust boundary type inferred from name/geometry/rating — confirm the real boundary type",
}

// buildScaffoldYAML marshals model to the authoring YAML format (via
// modelToInput, same as plain output) and then attaches TODO(review)
// head-comments to every importer-guessed field, plus a file header
// describing the source diagram, importer, and generated-element counts.
func buildScaffoldYAML(model *types.Model, importerName, sourceFile string) ([]byte, error) {
	in := modelToInput(model)

	plain, err := yaml.Marshal(in)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal model to YAML: %w", err)
	}

	var doc yaml.Node
	if err := yaml.Unmarshal(plain, &doc); err != nil {
		return nil, fmt.Errorf("failed to re-parse marshalled YAML for scaffolding: %w", err)
	}
	if len(doc.Content) == 0 || doc.Content[0].Kind != yaml.MappingNode {
		// Nothing to annotate (empty document) — fall back to plain output.
		return plain, nil
	}
	root := doc.Content[0]

	annotateSection(root, "technical_assets", scaffoldTechnicalAssetReasons)
	annotateSection(root, "data_assets", scaffoldDataAssetReasons)
	annotateSection(root, "trust_boundaries", scaffoldTrustBoundaryReasons)

	setHeaderComment(root, scaffoldHeader(model, importerName, sourceFile))

	out, err := yaml.Marshal(&doc)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal scaffolded YAML: %w", err)
	}
	return out, nil
}

// scaffoldHeader builds the file-header comment block: source, importer,
// generated-element counts, and a legend explaining the review markers.
func scaffoldHeader(model *types.Model, importerName, sourceFile string) string {
	if sourceFile == "" {
		sourceFile = "stdin"
	}
	var b strings.Builder
	fmt.Fprintf(&b, "Threagile scaffold generated by `threagile import %s` (deterministic, no AI).\n", importerName)
	fmt.Fprintf(&b, "Source: %s\n", sourceFile)
	fmt.Fprintf(&b, "Generated: %d technical asset(s), %d trust boundary(ies), %d communication link(s), %d data asset(s).\n",
		len(model.TechnicalAssets), len(model.TrustBoundaries), len(model.CommunicationLinks), len(model.DataAssets))
	b.WriteString("\n")
	b.WriteString("Legend: everything tagged review-" + importerName + " or carrying a TODO(review) comment\n")
	b.WriteString("was inferred/defaulted by the importer and needs human confirmation before\n")
	b.WriteString("this model is trusted for analysis. Re-run with --scaffold=false for plain output.")
	return b.String()
}

// setHeaderComment attaches text as a head-comment on the first key of a
// mapping node, which yaml.v3 renders above the whole document.
func setHeaderComment(mapping *yaml.Node, text string) {
	if mapping.Kind != yaml.MappingNode || len(mapping.Content) == 0 {
		return
	}
	mapping.Content[0].HeadComment = text
}

// annotateSection finds `root[sectionKey]` (a mapping of element-title ->
// element-mapping) and, for every element, attaches a "TODO(review): <why>"
// head-comment to each field named in fieldReasons.
func annotateSection(root *yaml.Node, sectionKey string, fieldReasons map[string]string) {
	section := mapValue(root, sectionKey)
	if section == nil || section.Kind != yaml.MappingNode {
		return
	}
	for i := 1; i < len(section.Content); i += 2 {
		element := section.Content[i]
		if element.Kind != yaml.MappingNode {
			continue
		}
		annotateFields(element, fieldReasons)
	}
}

// annotateFields walks the direct key/value pairs of a mapping node and sets
// a TODO(review) head-comment on every key whose name is in fieldReasons.
func annotateFields(mapping *yaml.Node, fieldReasons map[string]string) {
	for i := 0; i+1 < len(mapping.Content); i += 2 {
		key := mapping.Content[i]
		reason, ok := fieldReasons[key.Value]
		if !ok {
			continue
		}
		key.HeadComment = "TODO(review): " + reason
	}
}

// mapValue returns the value node for key in a mapping node, or nil.
func mapValue(mapping *yaml.Node, key string) *yaml.Node {
	if mapping.Kind != yaml.MappingNode {
		return nil
	}
	for i := 0; i+1 < len(mapping.Content); i += 2 {
		if mapping.Content[i].Value == key {
			return mapping.Content[i+1]
		}
	}
	return nil
}
