// Package drawio converts a draw.io / diagrams.net (mxGraph) diagram into a
// partial Threagile model. Unlike the threat-dragon importer, draw.io is a
// generic diagram format with no built-in threat-model semantics, so the
// conversion is deliberately conservative and LOSSY: shapes are classified by
// their style and label using deterministic rules, every generated asset is
// tagged "review-drawio", and ratings default conservatively for manual review.
// There is no AI in the loop.
//
//	model, err := drawio.Import(xmlBytes, drawio.ImportOptions{})
package drawio

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"encoding/xml"
	"errors"
	"fmt"
	"io"
	"net/url"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/threagile/threagile/pkg/import/mapping"
	"github.com/threagile/threagile/pkg/types"
)

var nonAlnum = regexp.MustCompile(`[^a-z0-9]+`)

func toID(parts ...string) string {
	return strings.Trim(nonAlnum.ReplaceAllString(strings.ToLower(strings.Join(parts, "-")), "-"), "-")
}

// ImportOptions controls import behaviour.
type ImportOptions struct {
	SourceLabel string // appended to generated asset IDs (default "drawio")

	// Mapping is an optional user-supplied mapping dictionary (P3) applied to
	// every vertex/edge right after it is classified, so corrections (e.g.
	// "MinIO" -> object-storage) land before P4 stub generation runs on the
	// resulting model. nil means no mapping rules are applied.
	Mapping *mapping.Ruleset

	// Page selects a single <diagram> page to import, by 1-based index
	// ("2") or by its draw.io page name (case-insensitive, e.g. "Overview").
	// Empty (default) processes every page in the file, merging them into
	// one model — each page's boundary/geometry containment stays scoped to
	// that page (a page-2 container never absorbs a page-1 shape), while
	// generated asset IDs stay globally unique across all merged pages.
	Page string

	// Boundary, when set, scopes the import to only the elements inside the
	// named trust boundary's subtree (its own contents plus any nested
	// boundaries' contents), skipping everything else. Matched
	// case-insensitively against the boundary's label. Applied after
	// pages/boundaries are built, so it composes with Page.
	Boundary string
}

// reviewTag flags every imported asset for manual review (draw.io is lossy).
const reviewTag = "review-drawio"

// maxInflatedBytes bounds decompression of a draw.io payload (anti-bomb).
const maxInflatedBytes = 32 << 20 // 32 MiB

type vertex struct {
	cell    mxCell
	label   string
	assetID string
}

// diagramPage is one <diagram> page's flattened cell list.
type diagramPage struct {
	name  string
	cells []mxCell
}

// Import parses a draw.io XML document and returns a partial *types.Model.
// By default every page in the file is imported and merged into one model
// (see ImportOptions.Page to restrict to a single page, and
// ImportOptions.Boundary to further scope to one trust boundary's subtree).
func Import(data []byte, opts ImportOptions) (*types.Model, error) {
	if opts.SourceLabel == "" {
		opts.SourceLabel = "drawio"
	}

	pages, err := parsePages(data)
	if err != nil {
		return nil, err
	}
	selected, err := selectPages(pages, opts.Page)
	if err != nil {
		return nil, err
	}
	if len(selected) == 0 {
		return nil, errors.New("drawio: no diagram cells found (export as uncompressed XML if your file is compressed)")
	}

	model := &types.Model{
		ThreagileVersion:   "1.0.0",
		Title:              "Imported from draw.io",
		TechnicalAssets:    make(map[string]*types.TechnicalAsset),
		TrustBoundaries:    make(map[string]*types.TrustBoundary),
		DataAssets:         make(map[string]*types.DataAsset),
		CommunicationLinks: make(map[string]*types.CommunicationLink),
		TagsAvailable:      []string{reviewTag},
	}

	b := &builder{model: model, label: opts.SourceLabel, mapping: opts.Mapping}

	for _, page := range selected {
		if len(page.cells) == 0 {
			continue
		}
		b.importPage(page.cells)
	}

	if opts.Boundary != "" {
		if err := scopeToBoundary(model, opts.Boundary); err != nil {
			return nil, err
		}
	}

	if len(model.TechnicalAssets) == 0 {
		return nil, errors.New("drawio: no shapes could be mapped to technical assets")
	}

	da := &types.DataAsset{
		Id:              toID("data-imported", opts.SourceLabel),
		Title:           "Imported Data (review and classify)",
		Description:     "Stub data asset generated by drawio import. Review confidentiality and PII fields.",
		Confidentiality: types.Confidential,
		Integrity:       types.Critical,
		Availability:    types.Critical,
		Tags:            []string{reviewTag},
	}
	model.DataAssets[da.Id] = da

	return model, nil
}

// importPage runs the vertex/edge/boundary passes for one page's cells,
// accumulating results into b.model. byID and verticesByCell are rebuilt
// per page (fresh, page-local maps) so a page's edges/containment can only
// ever resolve against that same page's cells — never a same-numbered cell
// id belonging to a different page. b.usedIDs (via uniqueID) is NOT reset
// between pages, so generated Threagile IDs stay globally unique across
// every merged page.
func (b *builder) importPage(cells []mxCell) {
	// Stable order for determinism — sort BEFORE indexing so the byID pointers
	// remain valid (sorting reorders the backing array).
	cells = append([]mxCell(nil), cells...)
	sort.SliceStable(cells, func(i, j int) bool { return cells[i].ID < cells[j].ID })

	byID := map[string]*mxCell{}
	for i := range cells {
		byID[cells[i].ID] = &cells[i]
	}
	b.byID = byID
	b.verticesByCell = map[string]*vertex{}

	var boundaryCells []mxCell
	for _, c := range cells {
		switch {
		case c.Edge == "1" || (c.Source != "" && c.Target != ""):
			// handled in the edge pass
		case c.Vertex == "1" && isBoundary(c):
			boundaryCells = append(boundaryCells, c)
		case c.Vertex == "1":
			b.buildVertexAsset(c)
		}
	}
	for _, c := range cells {
		if c.Edge == "1" || (c.Source != "" && c.Target != "") {
			b.buildEdgeLink(c)
		}
	}
	b.markInternetExposure(cells)
	b.assignBoundaries(boundaryCells)
}

// parsePages extracts every <diagram> page's flattened cell list, handling
// both uncompressed <mxGraphModel> and compressed (deflate+base64) payloads.
// A bare <mxGraphModel> document (no <mxfile> wrapper) is treated as a
// single unnamed page.
func parsePages(data []byte) ([]diagramPage, error) {
	data = sanitizeXML(data)
	if bytes.Contains(data, []byte("<mxGraphModel")) && !bytes.Contains(data, []byte("<mxfile")) {
		var model mxGraphModel
		if err := xml.Unmarshal(data, &model); err != nil {
			return nil, fmt.Errorf("drawio: failed to parse mxGraphModel XML: %w", err)
		}
		return []diagramPage{{cells: flattenRoot(model.Root)}}, nil
	}

	var file mxFile
	if err := xml.Unmarshal(data, &file); err != nil {
		return nil, fmt.Errorf("drawio: failed to parse XML: %w", err)
	}
	if len(file.Diagrams) == 0 {
		return nil, errors.New("drawio: no <diagram> elements found")
	}

	pages := make([]diagramPage, 0, len(file.Diagrams))
	for _, dg := range file.Diagrams {
		var cells []mxCell
		switch {
		case dg.Model != nil:
			cells = flattenRoot(dg.Model.Root)
		default:
			if model := decompressDiagram(dg.Content); model != nil {
				cells = flattenRoot(model.Root)
			}
		}
		pages = append(pages, diagramPage{name: dg.Name, cells: cells})
	}

	anyCells := false
	for _, p := range pages {
		if len(p.cells) > 0 {
			anyCells = true
			break
		}
	}
	if !anyCells {
		return nil, errors.New("drawio: diagram is compressed and could not be decoded — re-export with Extras → Edit Diagram (uncompressed) or File → Export as → XML (uncompressed)")
	}
	return pages, nil
}

// selectPages returns every page in pages when sel is empty, or just the one
// page matching sel (a 1-based index, e.g. "2", or a page name, matched
// case-insensitively) otherwise.
func selectPages(pages []diagramPage, sel string) ([]diagramPage, error) {
	if sel == "" {
		return pages, nil
	}
	if n, err := strconv.Atoi(sel); err == nil {
		if n < 1 || n > len(pages) {
			return nil, fmt.Errorf("drawio: --page %q is out of range (file has %d page(s))", sel, len(pages))
		}
		return pages[n-1 : n], nil
	}
	for _, p := range pages {
		if strings.EqualFold(p.name, sel) {
			return []diagramPage{p}, nil
		}
	}
	return nil, fmt.Errorf("drawio: no page named %q found", sel)
}

// htmlEntity matches the named HTML entities draw.io emits in labels (notably
// &nbsp;) that Go's XML parser rejects as undeclared. They are replaced with a
// space before unmarshalling (labels are whitespace-collapsed anyway).
var htmlEntity = regexp.MustCompile(`&(nbsp|ensp|emsp|thinsp|hellip|mdash|ndash|rsquo|lsquo|rdquo|ldquo|bull|middot|deg|copy|reg|trade);`)

func sanitizeXML(data []byte) []byte {
	return htmlEntity.ReplaceAll(data, []byte(" "))
}

// decompressDiagram decodes draw.io's base64 + raw-deflate + URL-encoded payload.
func decompressDiagram(content string) *mxGraphModel {
	content = strings.TrimSpace(content)
	if content == "" {
		return nil
	}
	raw, err := base64.StdEncoding.DecodeString(content)
	if err != nil {
		return nil
	}
	r := flate.NewReader(bytes.NewReader(raw))
	defer func() { _ = r.Close() }()
	// Bound the inflated size to guard against a decompression bomb in untrusted
	// input. 32 MiB is far larger than any real diagram.
	inflated, err := io.ReadAll(io.LimitReader(r, maxInflatedBytes))
	if err != nil || len(inflated) == 0 || int64(len(inflated)) >= maxInflatedBytes {
		return nil
	}
	unescaped, err := url.QueryUnescape(string(inflated))
	if err != nil {
		unescaped = string(inflated)
	}
	var model mxGraphModel
	if err := xml.Unmarshal(sanitizeXML([]byte(unescaped)), &model); err != nil {
		return nil
	}
	return &model
}

// flattenRoot merges direct mxCells and <object>-wrapped cells into one slice,
// carrying the object label onto its cell value.
func flattenRoot(root mxRoot) []mxCell {
	out := make([]mxCell, 0, len(root.Cells)+len(root.Objects))
	out = append(out, root.Cells...)
	for _, o := range root.Objects {
		c := o.Cell
		if c.ID == "" {
			c.ID = o.ID
		}
		if c.Value == "" {
			c.Value = o.Label
		}
		out = append(out, c)
	}
	return out
}

type builder struct {
	model          *types.Model
	label          string
	byID           map[string]*mxCell
	verticesByCell map[string]*vertex
	usedIDs        map[string]bool  // guards against toID collisions (node_1 vs node-1)
	mapping        *mapping.Ruleset // optional user-supplied mapping dictionary (P3)
}

// styleValue extracts the value of a "key=value" pair from a draw.io style
// string (semicolon-separated, e.g. "fillColor=#00AA00;dashed=1;"). Returns
// "" if the key is absent.
func styleValue(style, key string) string {
	for _, part := range strings.Split(style, ";") {
		kv := strings.SplitN(part, "=", 2)
		if len(kv) == 2 && kv[0] == key {
			return kv[1]
		}
	}
	return ""
}

// styleIsDashed reports whether a draw.io style marks the shape/edge dashed.
func styleIsDashed(style string) bool {
	v := styleValue(style, "dashed")
	return v == "1" || v == "true"
}

// mappingElement builds a mapping.Element from a cell's label and style,
// carrying whatever raw style metadata draw.io retains (fill/stroke color,
// dash state) — the only importer of the three (drawio/threat-dragon/otm)
// that has this information at all.
func mappingElement(label string, edge bool, style string) mapping.Element {
	el := mapping.Element{Label: label, Edge: edge, FillColor: styleValue(style, "fillColor")}
	if edge {
		el.Color = styleValue(style, "strokeColor")
		if styleIsDashed(style) {
			el.LineStyle = "dashed"
		} else {
			el.LineStyle = "solid"
		}
	}
	return el
}

// uniqueID returns base, or base-2/base-3/… if base is already taken, so two
// cells whose IDs normalise identically don't overwrite each other.
func (b *builder) uniqueID(base string) string {
	if b.usedIDs == nil {
		b.usedIDs = map[string]bool{}
	}
	id := base
	for n := 2; b.usedIDs[id]; n++ {
		id = fmt.Sprintf("%s-%d", base, n)
	}
	b.usedIDs[id] = true
	return id
}

func cellText(c mxCell) string {
	// draw.io labels can contain HTML; strip tags for a clean title.
	v := regexp.MustCompile(`<[^>]+>`).ReplaceAllString(c.Value, " ")
	return strings.TrimSpace(strings.Join(strings.Fields(v), " "))
}

func (b *builder) buildVertexAsset(c mxCell) {
	label := cellText(c)
	if label == "" {
		label = c.ID
	}
	id := b.uniqueID(toID(c.ID, b.label))
	assetType, tech := classifyVertex(c, label)

	asset := &types.TechnicalAsset{
		Id:              id,
		Title:           label,
		Description:     "Imported from draw.io shape (review classification)",
		Type:            assetType,
		Technologies:    types.TechnologyList{&types.Technology{Name: tech}},
		Machine:         types.Virtual,
		Internet:        assetType == types.ExternalEntity,
		Encryption:      types.NoneEncryption,
		Confidentiality: types.Confidential,
		Integrity:       types.Critical,
		Availability:    types.Critical,
		Tags:            []string{reviewTag},
	}
	if assetType == types.ExternalEntity {
		asset.UsedAsClientByHuman = true
	}
	mapping.ApplyToTechnicalAsset(b.mapping, asset, mappingElement(label, false, c.Style))
	b.model.TechnicalAssets[id] = asset
	b.verticesByCell[c.ID] = &vertex{cell: c, label: label, assetID: id}
}

var datastoreNames = []struct{ needle, tech string }{
	{"postgres", types.Database}, {"mysql", types.Database}, {"mariadb", types.Database},
	{"mongo", types.Database}, {"redis", types.Database}, {"cassandra", types.Database},
	{"sql", types.Database}, {"database", types.Database}, {"db", types.Database},
	{"elasticsearch", types.SearchEngine}, {"opensearch", types.SearchEngine},
	{"s3", types.FileServer}, {"bucket", types.FileServer}, {"blob", types.FileServer},
	{"minio", types.FileServer}, {"storage", types.FileServer},
	{"vault", types.Vault}, {"queue", types.MessageQueue}, {"kafka", types.MessageQueue},
}

func classifyVertex(c mxCell, label string) (types.TechnicalAssetType, string) {
	style := strings.ToLower(c.Style)
	name := strings.ToLower(label)
	hay := style + " " + name

	switch {
	case strings.Contains(style, "shape=actor") || strings.Contains(style, "umlactor") || styleHasUser(style) ||
		matchesAny(name, "user", "client", "browser", "customer", "actor", "attacker", "external", "third-party", "person"):
		return types.ExternalEntity, types.ClientSystem
	case strings.Contains(style, "cylinder") || strings.Contains(style, "datastore") || strings.Contains(style, ".database") ||
		hasWord(name, "db", "database", "store", "datastore", "postgres", "mysql", "mongo", "redis", "cache", "bucket", "s3", "queue", "sql", "minio"):
		for _, rule := range datastoreNames {
			if strings.Contains(hay, rule.needle) {
				return types.Datastore, rule.tech
			}
		}
		return types.Datastore, types.Database
	default:
		return types.Process, types.WebServer
	}
}

func styleHasUser(style string) bool {
	return strings.Contains(style, "mxgraph.") && strings.Contains(style, "user")
}

// isBoundary reports whether a vertex represents a trust boundary / zone. To
// avoid misclassifying ordinary shapes that merely mention "zone"/"vpc" in their
// label, a boundary keyword only counts when paired with a visual grouping style
// (dashed / container / group / swimlane) — or when the style itself names a
// trust-boundary shape.
func isBoundary(c mxCell) bool {
	style := strings.ToLower(c.Style)
	name := strings.ToLower(cellText(c))
	if strings.Contains(style, "trust") || strings.Contains(style, "boundary") {
		return true
	}
	grouping := strings.Contains(style, "container=1") || strings.Contains(style, "group") ||
		strings.Contains(style, "swimlane") || strings.Contains(style, "dashed=1")
	hasWord := matchesAny(name+" "+style, "trust", "boundary", "zone", "dmz", "perimeter",
		"vpc", "subnet", "untrusted", "internet", "network")
	return grouping && hasWord
}

func (b *builder) buildEdgeLink(c mxCell) {
	src, okS := b.verticesByCell[c.Source]
	dst, okT := b.verticesByCell[c.Target]
	if !okS || !okT || src.assetID == dst.assetID {
		return
	}
	title := cellText(c)
	if title == "" {
		title = src.cell.ID + " → " + dst.cell.ID
	}
	linkID := toID("link", c.Source, "to", c.Target, c.ID, b.label)
	if _, exists := b.model.CommunicationLinks[linkID]; exists {
		return
	}
	link := &types.CommunicationLink{
		Id:             linkID,
		SourceId:       src.assetID,
		TargetId:       dst.assetID,
		Title:          title,
		Description:    "Imported from draw.io flow (review protocol/auth)",
		Protocol:       guessProtocol(title),
		Authentication: types.NoneAuthentication,
		Authorization:  types.NoneAuthorization,
		Usage:          types.Business,
		Tags:           []string{reviewTag},
	}
	mapping.ApplyToCommunicationLink(b.mapping, link, mappingElement(title, true, c.Style))
	b.model.CommunicationLinks[linkID] = link
	srcAsset := b.model.TechnicalAssets[src.assetID]
	srcAsset.CommunicationLinks = append(srcAsset.CommunicationLinks, link)
}

func (b *builder) markInternetExposure(cells []mxCell) {
	for _, c := range cells {
		if c.Source == "" || c.Target == "" {
			continue
		}
		src, okS := b.verticesByCell[c.Source]
		dst, okT := b.verticesByCell[c.Target]
		if !okS || !okT {
			continue
		}
		if b.model.TechnicalAssets[src.assetID].Type == types.ExternalEntity {
			b.model.TechnicalAssets[dst.assetID].Internet = true
		}
	}
}

// assignBoundaries places each node inside a boundary by (a) the draw.io parent
// attribute (container case) or (b) absolute-geometry containment in the
// smallest boundary box.
func (b *builder) assignBoundaries(boundaries []mxCell) {
	boundaryIDs := map[string]string{} // cell id -> threagile boundary id
	var boxes []boundaryBox
	for _, bc := range boundaries {
		bID := b.uniqueID(toID("boundary", bc.ID, b.label))
		boundaryIDs[bc.ID] = bID
		bx := boundaryBox{cellID: bc.ID, bID: bID, title: cellText(bc), descr: "Imported from draw.io boundary"}
		if ax, ay, ok := b.absPos(bc.ID); ok && bc.Geometry != nil {
			bx.x, bx.y = ax, ay
			bx.w, bx.h = bc.Geometry.Width, bc.Geometry.Height
			bx.area = bx.w * bx.h
			bx.hasGeom = bx.area > 0
		}
		boxes = append(boxes, bx)
	}
	sort.SliceStable(boxes, func(i, j int) bool { return boxes[i].area < boxes[j].area })

	// parentOf resolves each boundary's own parent boundary (nested
	// container/swimlane -> nested trust boundary), to arbitrary depth: (a)
	// the draw.io `parent` attribute, if it names another boundary cell, else
	// (b) geometry containment in the smallest STRICTLY LARGER boundary box.
	parentOf := map[string]string{} // child bID -> parent bID
	for _, bc := range boundaries {
		childID := boundaryIDs[bc.ID]
		if pID, ok := boundaryIDs[bc.Parent]; ok && pID != childID {
			parentOf[childID] = pID
			continue
		}
		ax, ay, ok := b.absPos(bc.ID)
		if !ok || bc.Geometry == nil {
			continue
		}
		cx := ax + bc.Geometry.Width/2
		cy := ay + bc.Geometry.Height/2
		for _, bx := range boxes {
			if bx.bID == childID || !bx.hasGeom || bx.area <= 0 {
				continue
			}
			// Must be a proper superset in area to avoid a box containing
			// itself/an equal-area sibling.
			if bx.area <= boxFor(boxes, childID).area {
				continue
			}
			if cx >= bx.x && cx <= bx.x+bx.w && cy >= bx.y && cy <= bx.y+bx.h {
				parentOf[childID] = bx.bID
				break
			}
		}
	}
	nestedChildren := map[string][]string{} // parent bID -> child bIDs
	for child, parent := range parentOf {
		nestedChildren[parent] = append(nestedChildren[parent], child)
	}

	inside := map[string][]string{}
	for _, v := range b.sortedVertices() {
		// (a) parent-attribute membership.
		if bID, ok := boundaryIDs[v.cell.Parent]; ok {
			inside[bID] = append(inside[bID], v.assetID)
			continue
		}
		// (b) geometry containment in the smallest box.
		ax, ay, ok := b.absPos(v.cell.ID)
		if !ok || v.cell.Geometry == nil {
			continue
		}
		cx := ax + v.cell.Geometry.Width/2
		cy := ay + v.cell.Geometry.Height/2
		for _, bx := range boxes {
			if !bx.hasGeom {
				continue
			}
			if cx >= bx.x && cx <= bx.x+bx.w && cy >= bx.y && cy <= bx.y+bx.h {
				inside[bx.bID] = append(inside[bx.bID], v.assetID)
				break
			}
		}
	}

	for _, bx := range boxes {
		ids := inside[bx.bID]
		children := nestedChildren[bx.bID]
		if len(ids) == 0 && len(children) == 0 {
			continue
		}
		sort.Strings(ids)
		sort.Strings(children)
		title := bx.title
		if title == "" {
			title = bx.cellID
		}
		boundaryType := types.NetworkVirtualLAN
		if matchesAny(strings.ToLower(title), "internet", "untrusted", "public", "dmz") {
			boundaryType = types.NetworkOnPrem
		}
		b.model.TrustBoundaries[bx.bID] = &types.TrustBoundary{
			Id:                    bx.bID,
			Title:                 title,
			Description:           bx.descr,
			Type:                  boundaryType,
			Tags:                  []string{reviewTag},
			TechnicalAssetsInside: ids,
			TrustBoundariesNested: children,
		}
	}
}

// boundaryBox is one boundary cell's Threagile ID plus its absolute geometry
// (when known), used both for vertex-containment and for resolving
// boundary-inside-boundary nesting.
type boundaryBox struct {
	cellID           string
	bID              string
	x, y, w, h, area float64
	title, descr     string
	hasGeom          bool
}

// boxFor looks up a box by its Threagile boundary ID; callers only use this
// with an ID known to be in boxes, so a zero-value box is a safe fallback.
func boxFor(boxes []boundaryBox, bID string) boundaryBox {
	for _, bx := range boxes {
		if bx.bID == bID {
			return bx
		}
	}
	return boundaryBox{}
}

// absPos resolves a cell's absolute top-left position by summing geometry
// offsets up the parent chain (draw.io child geometry is parent-relative). It
// returns ok=false on malformed input — the starting cell lacking geometry, or a
// cyclic parent chain — so callers skip geometry-based membership rather than
// using fabricated coordinates.
func (b *builder) absPos(cellID string) (float64, float64, bool) {
	start, ok := b.byID[cellID]
	if !ok || start.Geometry == nil {
		return 0, 0, false
	}
	var x, y float64
	seen := map[string]bool{}
	id := cellID
	for id != "" {
		if seen[id] {
			return 0, 0, false // cyclic parent chain
		}
		seen[id] = true
		c, ok := b.byID[id]
		if !ok || c.Geometry == nil {
			break // reached a layer cell (no geometry) — chain complete
		}
		x += c.Geometry.X
		y += c.Geometry.Y
		id = c.Parent
	}
	return x, y, true
}

func (b *builder) sortedVertices() []*vertex {
	out := make([]*vertex, 0, len(b.verticesByCell))
	for _, v := range b.verticesByCell {
		out = append(out, v)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].assetID < out[j].assetID })
	return out
}

func matchesAny(haystack string, needles ...string) bool {
	for _, n := range needles {
		if strings.Contains(haystack, n) {
			return true
		}
	}
	return false
}

// hasWord reports whether any needle appears as a whole word in text (split on
// non-alphanumerics), so "db" matches "auth db" but not "dashboard".
func hasWord(text string, needles ...string) bool {
	words := nonAlnum.Split(strings.ToLower(text), -1)
	set := map[string]bool{}
	for _, w := range words {
		if w != "" {
			set[w] = true
		}
	}
	for _, n := range needles {
		if set[n] {
			return true
		}
	}
	return false
}

// scopeToBoundary prunes model down to just the elements inside the named
// trust boundary's subtree (the boundary's own directly-contained assets,
// plus every nested boundary's assets, to arbitrary depth) — the answer to
// "a 100+-node enterprise diagram produces an unreviewable 5000-line YAML":
// import one subsystem at a time. Matched case-insensitively against a trust
// boundary's Title. Communication links are kept only when both endpoints
// survive the prune; each surviving technical asset's own CommunicationLinks
// slice is filtered the same way so modelToInput doesn't re-emit dangling
// links.
func scopeToBoundary(model *types.Model, boundaryName string) error {
	var rootID string
	for id, tb := range model.TrustBoundaries {
		if strings.EqualFold(tb.Title, boundaryName) {
			rootID = id
			break
		}
	}
	if rootID == "" {
		return fmt.Errorf("drawio: no trust boundary named %q found (case-insensitive match on the boundary's label)", boundaryName)
	}

	keepBoundary := map[string]bool{}
	var walk func(id string)
	walk = func(id string) {
		if keepBoundary[id] {
			return
		}
		keepBoundary[id] = true
		tb, ok := model.TrustBoundaries[id]
		if !ok {
			return
		}
		for _, child := range tb.TrustBoundariesNested {
			walk(child)
		}
	}
	walk(rootID)

	keepAsset := map[string]bool{}
	for id := range keepBoundary {
		for _, assetID := range model.TrustBoundaries[id].TechnicalAssetsInside {
			keepAsset[assetID] = true
		}
	}

	for id := range model.TrustBoundaries {
		if !keepBoundary[id] {
			delete(model.TrustBoundaries, id)
		}
	}
	for id, ta := range model.TechnicalAssets {
		if !keepAsset[id] {
			delete(model.TechnicalAssets, id)
			continue
		}
		filtered := ta.CommunicationLinks[:0:0]
		for _, link := range ta.CommunicationLinks {
			if keepAsset[link.SourceId] && keepAsset[link.TargetId] {
				filtered = append(filtered, link)
			}
		}
		ta.CommunicationLinks = filtered
	}
	for id, link := range model.CommunicationLinks {
		if !keepAsset[link.SourceId] || !keepAsset[link.TargetId] {
			delete(model.CommunicationLinks, id)
		}
	}
	return nil
}

// guessProtocol classifies a communication link's protocol from its edge
// label, defaulting to HTTPS (a conservative "assume encrypted" default)
// when no keyword matches. Kept in lockstep with mermaid's identically-named
// function (pkg/import/mermaid/importer.go) so the two lossy diagram
// importers make the same guess for the same label — see
// docs/import-drawio.md / docs/import-mermaid.md for the documented table.
func guessProtocol(label string) types.Protocol {
	l := strings.ToLower(label)
	switch {
	case matchesAny(l, "https", "tls", "ssl"):
		return types.HTTPS
	case matchesAny(l, "grpc"):
		return types.HTTPS
	case matchesAny(l, "http"):
		return types.HTTP
	case matchesAny(l, "ssh"):
		return types.SSH
	case matchesAny(l, "sftp"):
		return types.SFTP
	case matchesAny(l, "ftps"):
		return types.FTPS
	case matchesAny(l, "ftp"):
		return types.FTP
	case matchesAny(l, "ldaps"):
		return types.LDAPS
	case matchesAny(l, "ldap"):
		return types.LDAP
	case matchesAny(l, "smtps", "smtp+tls"):
		return types.SmtpEncrypted
	case matchesAny(l, "smtp"):
		return types.SMTP
	case matchesAny(l, "mqtt"):
		return types.MQTT
	case matchesAny(l, "kafka", "amqp", "queue", "jms"):
		return types.JMS
	case matchesAny(l, "nfs"):
		return types.NFS
	case matchesAny(l, "smb", "cifs"):
		return types.SMB
	case matchesAny(l, "sql", "postgres", "mysql", "jdbc", "odbc"):
		return types.SqlAccessProtocolEncrypted
	case matchesAny(l, "nosql", "mongo", "redis"):
		return types.NosqlAccessProtocolEncrypted
	default:
		return types.HTTPS
	}
}
